/**
 * Data Model, Struktur Kategori Pos Keuangan (FINANCE_SCHEMA),
 * Daftar Dompet/Penyimpanan Dana Default, Mata Uang, Kamus Multi-Bahasa Lengkap, dan Utilitas Tanggal Real-Time.
 */

const DEFAULT_FINANCE_SCHEMA = {
  Income: {
    label: 'Pemasukan (Income)',
    noBudget: true,
    groups: [
      {
        groupName: 'Sumber Pemasukan',
        items: [
          { id: 'inc_utama', name: 'Pendapatan Utama', icon: 'briefcase', defaultBudget: 0, noBudget: true },
          { id: 'inc_tambahan', name: 'Sumber Tambahan', icon: 'sparkles', defaultBudget: 0, noBudget: true }
        ]
      }
    ]
  },
  Expense: {
    label: 'Pengeluaran (Expenses)',
    groups: [
      {
        groupName: 'Pos Pengeluaran',
        badgeColor: 'rose',
        items: [
          { id: 'exp_transportasi', name: 'Transportasi', icon: 'fuel', defaultBudget: 0 },
          { id: 'exp_internet', name: 'Internet', icon: 'wifi', defaultBudget: 0 },
          { id: 'exp_jajan', name: 'Jajan', icon: 'coffee', defaultBudget: 0 },
          { id: 'exp_sedekah', name: 'Sedekah', icon: 'heart-handshake', defaultBudget: 0 },
          { id: 'exp_lainnya', name: 'Lainnya', icon: 'layers', defaultBudget: 0 }
        ]
      }
    ]
  },
  Savings: {
    label: 'Tabungan (Savings)',
    groups: [
      {
        groupName: 'Pos Tabungan & Dana Simpanan',
        items: [
          { id: 'sav_darurat', name: 'Dana Darurat', icon: 'shield-check', defaultBudget: 0, noBudget: true },
          { id: 'sav_pendidikan', name: 'Tabungan Pendidikan', icon: 'graduation-cap', defaultBudget: 0 }
        ]
      }
    ]
  }
};

const DEFAULT_WALLETS = [];

/**
 * Terjemahan Nama Kategori Default agar ikut berubah sesuai bahasa yang dipilih
 */
const CATEGORY_TRANSLATIONS = {
  'Pendapatan Utama': {
    id: 'Pendapatan Utama',
    en: 'Primary Income',
    ms: 'Pendapatan Utama',
    ja: '主な収入',
    ko: '주 수입',
    zh: '主要收入',
    ar: 'الدخل الأساسي',
    es: 'Ingreso Principal'
  },
  'Sumber Tambahan': {
    id: 'Sumber Tambahan',
    en: 'Additional Source',
    ms: 'Sumber Tambahan',
    ja: '副収入',
    ko: '부가 수입',
    zh: '额外收入',
    ar: 'دخل إضافي',
    es: 'Fuente Adicional'
  },
  'Transportasi': {
    id: 'Transportasi',
    en: 'Transportation',
    ms: 'Pengangkutan',
    ja: '交通費',
    ko: '교통비',
    zh: '交通出行',
    ar: 'المواصلات',
    es: 'Transporte'
  },
  'Internet': {
    id: 'Internet',
    en: 'Internet',
    ms: 'Internet',
    ja: '通信・ネット',
    ko: '인터넷/통신',
    zh: '网络通讯',
    ar: 'الإنترنت',
    es: 'Internet'
  },
  'Jajan': {
    id: 'Jajan',
    en: 'Dining & Snacks',
    ms: 'Jajan & Makanan',
    ja: '飲食・おやつ',
    ko: '식비/간식',
    zh: '餐饮零食',
    ar: 'طعام ووجبات',
    es: 'Comida y Snacks'
  },
  'Sedekah': {
    id: 'Sedekah',
    en: 'Charity',
    ms: 'Sedekah',
    ja: '寄付・募金',
    ko: '기부/나눔',
    zh: '慈善捐助',
    ar: 'صدقة وتبرعات',
    es: 'Caridad'
  },
  'Lainnya': {
    id: 'Lainnya',
    en: 'Others',
    ms: 'Lain-lain',
    ja: 'その他',
    ko: '기타',
    zh: '其他',
    ar: 'أخرى',
    es: 'Otros'
  },
  'Dana Darurat': {
    id: 'Dana Darurat',
    en: 'Emergency Fund',
    ms: 'Dana Kecemasan',
    ja: '緊急資金',
    ko: '비상금',
    zh: '紧急备用金',
    ar: 'صندوق الطوارئ',
    es: 'Fondo de Emergencia'
  },
  'Tabungan Pendidikan': {
    id: 'Tabungan Pendidikan',
    en: 'Education Savings',
    ms: 'Simpanan Pendidikan',
    ja: '教育貯蓄',
    ko: '교육 저축',
    zh: '教育储蓄',
    ar: 'مدخرات التعليم',
    es: 'Ahorro Educativo'
  }
};

/**
 * Daftar Format Mata Uang yang Didukung
 */
const CURRENCIES = {
  IDR: {
    code: 'IDR',
    symbol: 'Rp',
    name: 'Rupiah Indonesia (Rp)',
    locale: 'id-ID',
    thousandSep: '.',
    decimalSep: ',',
    quickAmounts: [25000, 50000, 100000, 500000, 1000000]
  },
  USD: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar ($)',
    locale: 'en-US',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [10, 25, 50, 100, 500]
  },
  EUR: {
    code: 'EUR',
    symbol: '€',
    name: 'Euro (€)',
    locale: 'de-DE',
    thousandSep: '.',
    decimalSep: ',',
    quickAmounts: [10, 25, 50, 100, 500]
  },
  SGD: {
    code: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar (S$)',
    locale: 'en-SG',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [10, 25, 50, 100, 500]
  },
  MYR: {
    code: 'MYR',
    symbol: 'RM',
    name: 'Malaysian Ringgit (RM)',
    locale: 'ms-MY',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [20, 50, 100, 250, 500]
  },
  JPY: {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen (¥)',
    locale: 'ja-JP',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [1000, 3000, 5000, 10000, 50000]
  },
  GBP: {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound (£)',
    locale: 'en-GB',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [10, 25, 50, 100, 500]
  },
  AUD: {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar (A$)',
    locale: 'en-AU',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [10, 25, 50, 100, 500]
  },
  SAR: {
    code: 'SAR',
    symbol: 'SR',
    name: 'Saudi Riyal (SR)',
    locale: 'ar-SA',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [50, 100, 250, 500, 1000]
  },
  KRW: {
    code: 'KRW',
    symbol: '₩',
    name: 'South Korean Won (₩)',
    locale: 'ko-KR',
    thousandSep: ',',
    decimalSep: '.',
    quickAmounts: [10000, 30000, 50000, 100000, 500000]
  }
};

/**
 * Daftar Bahasa yang Didukung
 */
const SUPPORTED_LANGUAGES = [
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩', locale: 'id-ID' },
  { code: 'en', name: 'English (US)', flag: '🇺🇸', locale: 'en-US' },
  { code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾', locale: 'ms-MY' },
  { code: 'ja', name: '日本語 (Japanese)', flag: '🇯🇵', locale: 'ja-JP' },
  { code: 'ko', name: '한국어 (Korean)', flag: '🇰🇷', locale: 'ko-KR' },
  { code: 'zh', name: '中文 (Mandarin)', flag: '🇨🇳', locale: 'zh-CN' },
  { code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦', locale: 'ar-SA' },
  { code: 'es', name: 'Español (Spanish)', flag: '🇪🇸', locale: 'es-ES' }
];

const MONTHS_BY_LANG = {
  id: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  ms: ['Januari', 'Februari', 'Mac', 'April', 'Mei', 'Jun', 'Julai', 'Ogos', 'September', 'Oktober', 'November', 'Disember'],
  ja: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  zh: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  ar: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
  es: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
};

const MONTHS_SHORT_BY_LANG = {
  id: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'],
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  ms: ['Jan', 'Feb', 'Mac', 'Apr', 'Mei', 'Jun', 'Jul', 'Ogo', 'Sep', 'Okt', 'Nov', 'Dis'],
  ja: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  zh: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  ar: ['ينا', 'فبر', 'مار', 'أبر', 'ماي', 'يون', 'يول', 'أغس', 'سبت', 'أكت', 'نوف', 'ديس'],
  es: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
};

const I18N_TRANSLATIONS = {
  id: {
    nav_dashboard: 'Dashboard',
    nav_wallets: 'Wallet',
    nav_income: 'Pemasukan',
    nav_expense: 'Pengeluaran',
    nav_savings: 'Tabungan',
    nav_history: 'Riwayat Transaksi',
    nav_settings: 'Pengaturan',
    nav_home_mobile: 'Beranda',
    btn_budget_short: 'Budget',
    btn_add_tx: 'Tambah Transaksi',
    btn_edit_tx: 'Edit Transaksi',
    btn_monthly_budget: 'Budget Bulanan',
    open_month_period: 'Periode Bulan Terbuka',
    all_months_1_year: 'Semua Bulan (1 Tahun)',
    card_total_income: 'Total Pemasukan',
    card_total_expense: 'Total Pengeluaran',
    card_total_savings: 'Total Tabungan',
    card_total_balance: 'Total Saldo Bersih',
    btn_open_wallet: 'Buka Wallet',
    sec_analytics: 'Analitik Visual',
    chart_top_spending: 'Pengeluaran Terbesar',
    chart_top_spending_sub: 'Pos pengeluaran',
    chart_savings_dist: 'Distribusi Tabungan',
    chart_savings_dist_sub: 'Alokasi tabungan',
    chart_actual_vs_budget: 'Aktual vs Budget',
    chart_actual_vs_budget_sub: 'Pengeluaran vs budget per bulan',
    chart_actual_label: 'Aktual',
    chart_budget_label: 'Budget',
    chart_empty: 'Kosong',
    sec_recent_tx: 'Transaksi Terbaru',
    btn_view_all: 'Lihat Semua',
    empty_tx_period: 'Belum ada transaksi pada periode ini',
    // Wallet
    dashboard_total_all_balance: 'TOTAL SELURUH SALDO',
    dashboard_all_balance_desc: 'Total akumulasi saldo dari semua sumber dana (Rekening Bank, Dompet Digital & Kas Tunai).',
    btn_manage_wallets: 'Kelola Wallet',
    wallet_total_title: 'Total Saldo Wallet',
    wallet_hero_desc: 'Pantau & kelola saldo rekening bank, dompet digital (E-Wallet), dan uang tunai Anda di satu tempat.',
    btn_add_wallet: 'Tambah Wallet',
    wallet_cat_bank: 'Bank',
    wallet_cat_cash: 'Tunai',
    wallet_cat_ewallet: 'E-Wallet',
    wallet_account_unit: 'Akun',
    wallet_list_title: 'Daftar Penyimpanan Dana',
    wallet_list_desc: 'Pilih kategori untuk menampilkan rincian saldo masing-masing wallet Anda.',
    filter_all: 'Semua',
    wallet_empty_all_title: 'Belum Ada Wallet yang Tersimpan',
    wallet_empty_all_desc: 'Tambahkan rekening bank, dompet digital (E-Wallet), atau uang tunai (Cash) Anda agar seluruh saldo dan mutasi transaksi tercatat otomatis.',
    wallet_empty_bank_title: 'Belum Ada Rekening Bank',
    wallet_empty_bank_desc: 'Tambahkan rekening bank Anda (seperti BCA, BNI, BRI, Mandiri, atau SeaBank) untuk memantau saldo dan mutasi rekening.',
    wallet_empty_cash_title: 'Belum Ada Wallet Tunai (Cash)',
    wallet_empty_cash_desc: 'Tambahkan dompet uang tunai (Cash) untuk mencatat uang pegangan harian agar pengeluaran tunai tetap terpantau rapi.',
    wallet_empty_ewallet_title: 'Belum Ada Akun E-Wallet',
    wallet_empty_ewallet_desc: 'Tambahkan dompet digital Anda (seperti GoPay, DANA, OVO, atau ShopeePay) untuk memantau sisa saldo dan pembayaran harian.',
    wallet_btn_set_balance: 'Atur Saldo',
    wallet_stored_balance: 'Saldo Tersimpan',
    wallet_in: 'Masuk',
    wallet_out: 'Keluar',
    wallet_share: 'Proporsi Saldo',
    // Breakdown Tabs
    income_tab_title: 'Tab Pemasukan (Income)',
    income_tab_sub: 'Total dana masuk',
    btn_new_source: '+ Sumber Baru',
    btn_add_income: 'Tambah Pemasukan',
    th_income_source: 'Sumber Dana Masuk',
    th_income_share: 'Kontribusi (%)',
    th_income_bar: 'Proporsi Dana Masuk',
    th_income_total: 'Total Masuk',
    income_source_sub: 'Sumber pemasukan',
    expense_tab_title: 'Tab Pengeluaran (Expenses)',
    expense_tab_from_budget: 'dari budget',
    btn_new_category: '+ Kategori Baru',
    btn_add_expense: 'Tambah Pengeluaran',
    savings_tab_title: 'Tab Tabungan (Savings)',
    savings_tab_target: 'Target terencana:',
    btn_add_savings: 'Tambah Tabungan',
    th_category: 'Kategori',
    th_tracked: 'Tercatat',
    th_budget: 'Budget',
    th_usage_pct: '% Pakai',
    th_visual_bar: 'Progress Visual',
    th_budget_left: 'Sisa Budget',
    th_excess: 'Kelebihan',
    badge_flexible_no_min: 'Fleksibel • Tanpa Minimal',
    label_no_min: 'Tanpa Minimal',
    badge_ready_use: 'Siap Pakai',
    label_emergency_balance: 'Saldo Dana Darurat',
    label_emergency_sub: 'Bisa dipakai kapan saja saat mendesak',
    badge_overbudget: 'Melebihi Budget (>100%)',
    // History
    history_title: 'Riwayat Transaksi',
    tx_unit: 'Transaksi',
    btn_reset_short: 'Reset',
    search_placeholder: 'Cari kategori, wallet, catatan...',
    all_types: 'Semua Tipe',
    th_date: 'Tanggal',
    th_type: 'Tipe',
    th_cat_note: 'Kategori & Catatan',
    th_wallet: 'Wallet',
    th_amount: 'Jumlah',
    th_action: 'Aksi',
    // Settings
    settings_appearance_title: 'Tampilan, Mata Uang & Bahasa',
    settings_appearance_desc: 'Atur Dual Mode (Gelap/Terang), format mata uang, dan bahasa aplikasi',
    settings_theme_label: 'Mode Tampilan (Dual Mode)',
    theme_dark: 'Gelap',
    theme_light: 'Terang',
    settings_currency_label: 'Format Mata Uang',
    settings_language_label: 'Pilihan Bahasa',
    settings_security_title: 'Kata Sandi & Keamanan',
    settings_security_desc: 'Kunci aplikasi dengan PIN, Pola, atau Sidik Jari perangkat',
    sec_status_inactive: 'Nonaktif',
    sec_status_active: 'Aktif',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'Pola',
    sec_method_fingerprint: 'Sidik Jari',
    sec_active_method_label: 'Metode Aktif:',
    btn_lock_now: 'Kunci Sekarang',
    btn_change_pass: 'Ubah Sandi',
    btn_disable_pass: 'Matikan Sandi',
    fp_not_available_device: 'Sensor Sidik Jari tidak tersedia di perangkat ini',
    fp_not_supported_toast: 'Perangkat ini tidak memiliki sensor Sidik Jari yang didukung, sehingga tidak dapat digunakan.',
    settings_backup_title: 'Cadangan Otomatis di Google Drive',
    settings_backup_desc: 'Cadangkan berkas transaksi otomatis di belakang layar agar aman saat ganti perangkat',
    badge_not_logged_in: 'Belum Login',
    badge_auto_sync: 'Auto-Sync Aktif',
    badge_connected: 'Terhubung',
    backup_device_sync_title: 'Sinkronisasi Akun Google Perangkat',
    backup_device_sync_desc: 'Klik tombol "Cadangkan Transaksi Anda" di bawah untuk otomatis mendeteksi akun Google di perangkat ini dan login terlebih dahulu.',
    backup_detected_on: 'Terdeteksi pada',
    btn_switch_account: 'Ganti Akun',
    btn_logout: 'Keluar',
    backup_auto_bg_label: 'Cadangan Otomatis di Belakang Layar (Google Drive)',
    bg_sync_connecting: 'Menghubungkan ke Google Drive di belakang layar...',
    bg_sync_uploading: 'Mencadangkan transaksi & wallet ke Google Drive...',
    bg_sync_done: 'Tersinkronisasi otomatis dengan Google Drive!',
    btn_backup_transactions: 'Cadangkan Transaksi Anda',
    btn_restore_transactions: 'Pulihkan Cadangan',
    btn_import_backup: 'Impor Berkas Cadangan',
    backup_history_title: 'Riwayat Cadangan Transaksi',
    backup_unit: 'Cadangan',
    backup_history_empty: 'Belum ada berkas cadangan transaksi di Google Drive.',
    settings_report_title: 'Unduh Laporan PDF & Manajemen Data',
    settings_report_desc: 'Download laporan PDF langsung otomatis tanpa login & kelola berkas',
    btn_download_pdf_direct: 'Download Laporan (PDF)',
    btn_full_history: 'Riwayat Transaksi Lengkap',
    btn_export_csv: 'Ekspor Transaksi ke CSV',
    btn_clear_all: 'Kosongkan Semua Nominal',
    // Modals & Lock Screen
    modal_tx_type_label: 'Tipe Transaksi',
    modal_tx_cat_label: 'Kategori',
    modal_tx_add_custom_cat: 'Tambah Kategori Sendiri',
    modal_tx_amount_label: 'Jumlah',
    modal_tx_date_label: 'Tanggal',
    modal_tx_wallet_label: 'Wallet',
    modal_tx_no_wallet: 'Tanpa Wallet',
    modal_tx_note_label: 'Catatan',
    modal_tx_optional: '(Opsional)',
    modal_tx_note_placeholder: 'Tulis keterangan singkat...',
    btn_cancel: 'Batal',
    btn_save_tx: 'Simpan Transaksi',
    btn_update_tx: 'Perbarui Transaksi',
    modal_cat_title: 'Tambah Kategori Baru',
    modal_cat_group_label: 'Kelompok Pos',
    modal_cat_name_label: 'Nama Kategori Baru',
    modal_cat_name_placeholder: 'Contoh: Tabungan Rumah / Liburan...',
    btn_add: 'Tambahkan',
    modal_wallet_bal_title: 'Atur Saldo',
    modal_wallet_bal_label: 'Saldo Saat Ini',
    btn_save_balance: 'Simpan Saldo',
    modal_new_wallet_title: 'Tambah Wallet Baru',
    modal_new_wallet_type: 'Jenis Wallet',
    modal_new_wallet_name: 'Nama Wallet',
    modal_new_wallet_placeholder: 'Ketik nama Bank / E-Wallet / Cash...',
    modal_new_wallet_initial: 'Saldo Awal',
    btn_save_wallet: 'Simpan Wallet',
    modal_budget_period: 'Periode:',
    modal_budget_note: 'Pos Pemasukan (Income) dan Dana Darurat bersifat fleksibel sehingga tidak memerlukan minimal/target budget bulanan.',
    btn_save_budget: 'Simpan Budget',
    modal_google_title: 'Deteksi Akun Google Perangkat',
    modal_google_sub: 'Login untuk menghubungkan Cadangan Transaksi ke Google Drive',
    modal_google_scanning_title: 'Mendeteksi Akun Google di Perangkat Ini...',
    modal_google_scanning_sub: 'Memeriksa sesi akun Google yang tersimpan pada perangkat Anda',
    modal_google_detected_label: 'Akun Google Terdeteksi di Perangkat',
    modal_google_pick_btn: 'Pilih & Login',
    modal_google_info: 'Wajib login terlebih dahulu. Setelah login dan menekan "Cadangkan Transaksi Anda", aplikasi akan otomatis berjalan di belakang layar ke Google Drive.',
    modal_google_name_label: 'Nama Akun Google Perangkat',
    modal_google_email_label: 'Alamat Email Google (Gmail) di Perangkat',
    btn_login_connect_device: 'Login & Hubungkan Perangkat',
    modal_sec_title: 'Atur Kata Sandi',
    modal_sec_sub: 'Pilih metode penguncian aplikasi',
    sec_pin_setup_title: 'Buat 6 Digit PIN Keamanan',
    sec_pin_setup_sub: 'Tekan angka di bawah untuk mengatur PIN baru',
    btn_save_pin: 'Simpan & Aktifkan PIN',
    sec_pattern_setup_title: 'Gambar Pola Kunci (Minimal 4 Titik)',
    sec_pattern_setup_sub: 'Hubungkan titik-titik pada grid 3x3 di bawah ini',
    btn_reset_pattern: 'Ulangi Pola',
    btn_save_pattern: 'Simpan Pola',
    sec_fp_setup_title: 'Sidik Jari Perangkat (Biometrik)',
    sec_fp_setup_sub: 'Gunakan sensor sidik jari bawaan pada perangkat Anda untuk mengunci aplikasi.',
    sec_fp_click_scan: 'Ketuk sensor untuk memindai sidik jari perangkat',
    lock_screen_title: 'FinanceTracker Terkunci',
    lock_screen_pin_prompt: 'Masukkan 6 digit PIN keamanan Anda',
    lock_screen_pattern_prompt: 'Gambar Pola Kunci Anda pada titik 3x3 di bawah',
    lock_screen_fp_prompt: 'Verifikasi sensor sidik jari perangkat Anda untuk membuka kunci',
    lock_screen_forgot: 'Lupa Sandi? Reset Kunci'
  },
  en: {
    nav_dashboard: 'Dashboard',
    nav_wallets: 'Wallets',
    nav_income: 'Income',
    nav_expense: 'Expenses',
    nav_savings: 'Savings',
    nav_history: 'Transactions',
    nav_settings: 'Settings',
    nav_home_mobile: 'Home',
    btn_budget_short: 'Budget',
    btn_add_tx: 'Add Transaction',
    btn_edit_tx: 'Edit Transaction',
    btn_monthly_budget: 'Monthly Budget',
    open_month_period: 'Available Months',
    all_months_1_year: 'All Months (1 Year)',
    card_total_income: 'Total Income',
    card_total_expense: 'Total Expenses',
    card_total_savings: 'Total Savings',
    card_total_balance: 'Total Balance',
    btn_open_wallet: 'Open Wallets',
    sec_analytics: 'Visual Analytics',
    chart_top_spending: 'Top Spending',
    chart_top_spending_sub: 'Expense categories',
    chart_savings_dist: 'Savings Dist.',
    chart_savings_dist_sub: 'Savings allocation',
    chart_actual_vs_budget: 'Actual vs Budget',
    chart_actual_vs_budget_sub: 'Monthly spending vs budget',
    chart_actual_label: 'Actual',
    chart_budget_label: 'Budget',
    chart_empty: 'Empty',
    sec_recent_tx: 'Recent Transactions',
    btn_view_all: 'View All',
    empty_tx_period: 'No transactions recorded in this period',
    dashboard_total_all_balance: 'TOTAL ALL BALANCES',
    dashboard_all_balance_desc: 'Accumulated balance from all active sources (Bank accounts, E-Wallets & Cash).',
    btn_manage_wallets: 'Manage Wallets',
    wallet_total_title: 'Total Wallet Balance',
    wallet_hero_desc: 'Monitor & manage your bank accounts, e-wallets, and cash balances in one place.',
    btn_add_wallet: 'Add Wallet',
    wallet_cat_bank: 'Bank',
    wallet_cat_cash: 'Cash',
    wallet_cat_ewallet: 'E-Wallet',
    wallet_account_unit: 'Accounts',
    wallet_list_title: 'Fund Storage List',
    wallet_list_desc: 'Select a category to view the detailed balance of each wallet.',
    filter_all: 'All',
    wallet_empty_all_title: 'No Wallets Saved Yet',
    wallet_empty_all_desc: 'Add your bank accounts, digital wallets (E-Wallet), or cash so all balances and transactions are tracked automatically.',
    wallet_empty_bank_title: 'No Bank Accounts Yet',
    wallet_empty_bank_desc: 'Add your bank account to monitor savings and account transactions.',
    wallet_empty_cash_title: 'No Cash Wallets Yet',
    wallet_empty_cash_desc: 'Add a cash wallet to track daily cash on hand.',
    wallet_empty_ewallet_title: 'No E-Wallet Accounts Yet',
    wallet_empty_ewallet_desc: 'Add your digital wallet to monitor balances and daily payments.',
    wallet_btn_set_balance: 'Set Balance',
    wallet_stored_balance: 'Stored Balance',
    wallet_in: 'In',
    wallet_out: 'Out',
    wallet_share: 'Balance Share',
    income_tab_title: 'Income Breakdown',
    income_tab_sub: 'Total incoming funds',
    btn_new_source: '+ New Source',
    btn_add_income: 'Add Income',
    th_income_source: 'Income Source',
    th_income_share: 'Share (%)',
    th_income_bar: 'Income Proportion',
    th_income_total: 'Total In',
    income_source_sub: 'Income source',
    expense_tab_title: 'Expenses Breakdown',
    expense_tab_from_budget: 'of budget',
    btn_new_category: '+ New Category',
    btn_add_expense: 'Add Expense',
    savings_tab_title: 'Savings Breakdown',
    savings_tab_target: 'Planned target:',
    btn_add_savings: 'Add Savings',
    th_category: 'Category',
    th_tracked: 'Tracked',
    th_budget: 'Budget',
    th_usage_pct: '% Usage',
    th_visual_bar: 'Visual Progress Bar',
    th_budget_left: 'Budget Left',
    th_excess: 'Excess',
    badge_flexible_no_min: 'Flexible • No Minimum',
    label_no_min: 'No Minimum',
    badge_ready_use: 'Ready to Use',
    label_emergency_balance: 'Emergency Fund Balance',
    label_emergency_sub: 'Available anytime for emergencies',
    badge_overbudget: 'Over Budget (>100%)',
    history_title: 'Transaction History',
    tx_unit: 'Transactions',
    btn_reset_short: 'Reset',
    search_placeholder: 'Search category, wallet, note...',
    all_types: 'All Types',
    th_date: 'Date',
    th_type: 'Type',
    th_cat_note: 'Category & Note',
    th_wallet: 'Wallet',
    th_amount: 'Amount',
    th_action: 'Action',
    settings_appearance_title: 'Appearance, Currency & Language',
    settings_appearance_desc: 'Configure Dual Mode (Dark/Light), currency format, and app language',
    settings_theme_label: 'Display Mode (Dual Mode)',
    theme_dark: 'Dark',
    theme_light: 'Light',
    settings_currency_label: 'Currency Format',
    settings_language_label: 'App Language',
    settings_security_title: 'Password & Security',
    settings_security_desc: 'Lock app using PIN, Pattern, or Device Fingerprint',
    sec_status_inactive: 'Inactive',
    sec_status_active: 'Active',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'Pattern',
    sec_method_fingerprint: 'Fingerprint',
    sec_active_method_label: 'Active Method:',
    btn_lock_now: 'Lock Now',
    btn_change_pass: 'Change Lock',
    btn_disable_pass: 'Disable Lock',
    fp_not_available_device: 'Fingerprint sensor is not available on this device',
    fp_not_supported_toast: 'This device does not have a supported Fingerprint sensor, so it cannot be used.',
    settings_backup_title: 'Automatic Google Drive Backup',
    settings_backup_desc: 'Back up transaction files in the background so you never start from 0 on a new device',
    badge_not_logged_in: 'Not Logged In',
    badge_auto_sync: 'Auto-Sync On',
    badge_connected: 'Connected',
    backup_device_sync_title: 'Device Google Account Sync',
    backup_device_sync_desc: 'Click "Back Up Your Transactions" below to automatically detect the Google account on this device and log in first.',
    backup_detected_on: 'Detected on',
    btn_switch_account: 'Switch Account',
    btn_logout: 'Sign Out',
    backup_auto_bg_label: 'Background Auto-Backup (Google Drive)',
    bg_sync_connecting: 'Connecting to Google Drive in the background...',
    bg_sync_uploading: 'Backing up transactions & wallets to Google Drive...',
    bg_sync_done: 'Automatically synced with Google Drive!',
    btn_backup_transactions: 'Back Up Your Transactions',
    btn_restore_transactions: 'Restore Backup',
    btn_import_backup: 'Import Backup File',
    backup_history_title: 'Transaction Backup History',
    backup_unit: 'Backups',
    backup_history_empty: 'No transaction backup files in Google Drive yet.',
    settings_report_title: 'PDF Report & Data Management',
    settings_report_desc: 'Instant PDF report download without login & manage your data',
    btn_download_pdf_direct: 'Download Report (PDF)',
    btn_full_history: 'Full Transaction History',
    btn_export_csv: 'Export Transactions to CSV',
    btn_clear_all: 'Reset All Balances to 0',
    modal_tx_type_label: 'Transaction Type',
    modal_tx_cat_label: 'Category',
    modal_tx_add_custom_cat: 'Add Custom Category',
    modal_tx_amount_label: 'Amount',
    modal_tx_date_label: 'Date',
    modal_tx_wallet_label: 'Wallet',
    modal_tx_no_wallet: 'No Wallet',
    modal_tx_note_label: 'Note',
    modal_tx_optional: '(Optional)',
    modal_tx_note_placeholder: 'Write a short note...',
    btn_cancel: 'Cancel',
    btn_save_tx: 'Save Transaction',
    btn_update_tx: 'Update Transaction',
    modal_cat_title: 'Add New Category',
    modal_cat_group_label: 'Category Group',
    modal_cat_name_label: 'New Category Name',
    modal_cat_name_placeholder: 'e.g., Home Savings / Vacation...',
    btn_add: 'Add',
    modal_wallet_bal_title: 'Set Balance',
    modal_wallet_bal_label: 'Current Balance',
    btn_save_balance: 'Save Balance',
    modal_new_wallet_title: 'Add New Wallet',
    modal_new_wallet_type: 'Wallet Type',
    modal_new_wallet_name: 'Wallet Name',
    modal_new_wallet_placeholder: 'Type Bank / E-Wallet / Cash name...',
    modal_new_wallet_initial: 'Initial Balance',
    btn_save_wallet: 'Save Wallet',
    modal_budget_period: 'Period:',
    modal_budget_note: 'Income and Emergency Fund are flexible and do not require a monthly target budget.',
    btn_save_budget: 'Save Budget',
    modal_google_title: 'Detect Device Google Account',
    modal_google_sub: 'Sign in to connect Transaction Backup to Google Drive',
    modal_google_scanning_title: 'Detecting Google Accounts on This Device...',
    modal_google_scanning_sub: 'Checking saved Google account sessions on your device',
    modal_google_detected_label: 'Detected Google Accounts on Device',
    modal_google_pick_btn: 'Select & Sign In',
    modal_google_info: 'Sign-in is required first. After signing in and pressing "Back Up Your Transactions", it will automatically sync in the background to Google Drive.',
    modal_google_name_label: 'Device Google Account Name',
    modal_google_email_label: 'Device Google Email (Gmail)',
    btn_login_connect_device: 'Sign In & Connect Device',
    modal_sec_title: 'Set Password Lock',
    modal_sec_sub: 'Choose an app locking method',
    sec_pin_setup_title: 'Create 6-Digit Security PIN',
    sec_pin_setup_sub: 'Tap numbers below to set your new PIN',
    btn_save_pin: 'Save & Enable PIN',
    sec_pattern_setup_title: 'Draw Pattern Lock (Min. 4 Dots)',
    sec_pattern_setup_sub: 'Connect dots on the 3x3 grid below',
    btn_reset_pattern: 'Reset Pattern',
    btn_save_pattern: 'Save Pattern',
    sec_fp_setup_title: 'Device Fingerprint (Biometric)',
    sec_fp_setup_sub: 'Use your device hardware fingerprint sensor to lock the app.',
    sec_fp_click_scan: 'Tap sensor to verify device fingerprint',
    lock_screen_title: 'FinanceTracker Locked',
    lock_screen_pin_prompt: 'Enter your 6-digit security PIN',
    lock_screen_pattern_prompt: 'Draw your unlock pattern on the 3x3 grid',
    lock_screen_fp_prompt: 'Verify your device fingerprint sensor to unlock',
    lock_screen_forgot: 'Forgot Password? Reset Lock'
  },
  ms: {
    nav_dashboard: 'Papan Pemuka',
    nav_wallets: 'Dompet',
    nav_income: 'Pendapatan',
    nav_expense: 'Perbelanjaan',
    nav_savings: 'Simpanan',
    nav_history: 'Sejarah Transaksi',
    nav_settings: 'Tetapan',
    nav_home_mobile: 'Utama',
    btn_budget_short: 'Bajet',
    btn_add_tx: 'Tambah Transaksi',
    btn_edit_tx: 'Edit Transaksi',
    btn_monthly_budget: 'Bajet Bulanan',
    open_month_period: 'Tempoh Bulan Dibuka',
    all_months_1_year: 'Semua Bulan (1 Tahun)',
    card_total_income: 'Jumlah Pendapatan',
    card_total_expense: 'Jumlah Perbelanjaan',
    card_total_savings: 'Jumlah Simpanan',
    card_total_balance: 'Baki Semasa',
    btn_open_wallet: 'Buka Dompet',
    sec_analytics: 'Analitik Visual',
    chart_top_spending: 'Perbelanjaan Utama',
    chart_top_spending_sub: 'Kategori perbelanjaan',
    chart_savings_dist: 'Agihan Simpanan',
    chart_savings_dist_sub: 'Peruntukan simpanan',
    chart_actual_vs_budget: 'Sebenar vs Bajet',
    chart_actual_vs_budget_sub: 'Perbelanjaan vs bajet bulanan',
    chart_actual_label: 'Sebenar',
    chart_budget_label: 'Bajet',
    chart_empty: 'Kosong',
    sec_recent_tx: 'Transaksi Terkini',
    btn_view_all: 'Lihat Semua',
    empty_tx_period: 'Tiada transaksi direkodkan pada tempoh ini',
    dashboard_total_all_balance: 'JUMLAH KESELURUHAN BAKI',
    dashboard_all_balance_desc: 'Jumlah baki terkumpul dari semua sumber dana (Akaun Bank, E-Dompet & Tunai).',
    btn_manage_wallets: 'Urus Dompet',
    wallet_total_title: 'Jumlah Baki Dompet',
    wallet_hero_desc: 'Pantau & urus baki akaun bank, e-dompet, dan tunai anda di satu tempat.',
    btn_add_wallet: 'Tambah Dompet',
    wallet_cat_bank: 'Bank',
    wallet_cat_cash: 'Tunai',
    wallet_cat_ewallet: 'E-Dompet',
    wallet_account_unit: 'Akaun',
    wallet_list_title: 'Senarai Penyimpanan Dana',
    wallet_list_desc: 'Pilih kategori untuk memaparkan butiran baki setiap dompet.',
    filter_all: 'Semua',
    wallet_empty_all_title: 'Belum Ada Dompet Disimpan',
    wallet_empty_all_desc: 'Tambah akaun bank, e-dompet, atau tunai anda supaya semua baki direkodkan secara automatik.',
    wallet_empty_bank_title: 'Belum Ada Akaun Bank',
    wallet_empty_bank_desc: 'Tambah akaun bank anda untuk memantau baki simpanan.',
    wallet_empty_cash_title: 'Belum Ada Dompet Tunai',
    wallet_empty_cash_desc: 'Tambah dompet tunai untuk mencatat perbelanjaan harian.',
    wallet_empty_ewallet_title: 'Belum Ada Akaun E-Dompet',
    wallet_empty_ewallet_desc: 'Tambah e-dompet anda untuk memantau baki pembayaran.',
    wallet_btn_set_balance: 'Tetapkan Baki',
    wallet_stored_balance: 'Baki Tersimpan',
    wallet_in: 'Masuk',
    wallet_out: 'Keluar',
    wallet_share: 'Nisbah Baki',
    income_tab_title: 'Tab Pendapatan (Income)',
    income_tab_sub: 'Jumlah dana masuk',
    btn_new_source: '+ Sumber Baharu',
    btn_add_income: 'Tambah Pendapatan',
    th_income_source: 'Sumber Dana Masuk',
    th_income_share: 'Sumbangan (%)',
    th_income_bar: 'Nisbah Dana Masuk',
    th_income_total: 'Jumlah Masuk',
    income_source_sub: 'Sumber pendapatan',
    expense_tab_title: 'Tab Perbelanjaan (Expenses)',
    expense_tab_from_budget: 'daripada bajet',
    btn_new_category: '+ Kategori Baharu',
    btn_add_expense: 'Tambah Perbelanjaan',
    savings_tab_title: 'Tab Simpanan (Savings)',
    savings_tab_target: 'Sasaran dirancang:',
    btn_add_savings: 'Tambah Simpanan',
    th_category: 'Kategori',
    th_tracked: 'Direkod',
    th_budget: 'Bajet',
    th_usage_pct: '% Guna',
    th_visual_bar: 'Bar Kemajuan',
    th_budget_left: 'Baki Bajet',
    th_excess: 'Lebihan',
    badge_flexible_no_min: 'Fleksibel • Tiada Minimum',
    label_no_min: 'Tiada Minimum',
    badge_ready_use: 'Sedia Digunakan',
    label_emergency_balance: 'Baki Dana Kecemasan',
    label_emergency_sub: 'Boleh digunakan bila-bila masa kecemasan',
    badge_overbudget: 'Melebihi Bajet (>100%)',
    history_title: 'Sejarah Transaksi',
    tx_unit: 'Transaksi',
    btn_reset_short: 'Reset',
    search_placeholder: 'Cari kategori, dompet, nota...',
    all_types: 'Semua Jenis',
    th_date: 'Tarikh',
    th_type: 'Jenis',
    th_cat_note: 'Kategori & Nota',
    th_wallet: 'Dompet',
    th_amount: 'Jumlah',
    th_action: 'Tindakan',
    settings_appearance_title: 'Paparan, Mata Wang & Bahasa',
    settings_appearance_desc: 'Tetapkan Mod Dwi (Gelap/Cerah), format mata wang, dan bahasa',
    settings_theme_label: 'Mod Paparan (Dual Mode)',
    theme_dark: 'Gelap',
    theme_light: 'Cerah',
    settings_currency_label: 'Format Mata Wang',
    settings_language_label: 'Pilihan Bahasa',
    settings_security_title: 'Kata Laluan & Keselamatan',
    settings_security_desc: 'Kunci aplikasi dengan PIN, Corak, atau Cap Jari peranti',
    sec_status_inactive: 'Tidak Aktif',
    sec_status_active: 'Aktif',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'Corak',
    sec_method_fingerprint: 'Cap Jari',
    sec_active_method_label: 'Kaedah Aktif:',
    btn_lock_now: 'Kunci Sekarang',
    btn_change_pass: 'Tukar Kunci',
    btn_disable_pass: 'Matikan Kunci',
    fp_not_available_device: 'Penderia Cap Jari tidak tersedia pada peranti ini',
    fp_not_supported_toast: 'Peranti ini tidak mempunyai penderia Cap Jari yang disokong, jadi ia tidak boleh digunakan.',
    settings_backup_title: 'Sandaran Automatik Google Drive',
    settings_backup_desc: 'Sandarkan transaksi di latar belakang supaya selamat apabila bertukar peranti',
    badge_not_logged_in: 'Belum Log Masuk',
    badge_auto_sync: 'Auto-Sync Aktif',
    badge_connected: 'Bersambung',
    backup_device_sync_title: 'Penyegerakan Akaun Google Peranti',
    backup_device_sync_desc: 'Klik "Sandarkan Transaksi Anda" di bawah untuk mengesan akaun Google pada peranti ini dan log masuk dahulu.',
    backup_detected_on: 'Dikesan pada',
    btn_switch_account: 'Tukar Akaun',
    btn_logout: 'Log Keluar',
    backup_auto_bg_label: 'Sandaran Automatik Latar Belakang (Google Drive)',
    bg_sync_connecting: 'Menyambung ke Google Drive di latar belakang...',
    bg_sync_uploading: 'Menyandarkan transaksi & dompet ke Google Drive...',
    bg_sync_done: 'Disegerakkan secara automatik dengan Google Drive!',
    btn_backup_transactions: 'Sandarkan Transaksi Anda',
    btn_restore_transactions: 'Pulihkan Sandaran',
    btn_import_backup: 'Import Fail Sandaran',
    backup_history_title: 'Sejarah Sandaran Transaksi',
    backup_unit: 'Sandaran',
    backup_history_empty: 'Tiada fail sandaran transaksi di Google Drive lagi.',
    settings_report_title: 'Laporan PDF & Pengurusan Data',
    settings_report_desc: 'Muat turun laporan PDF terus secara automatik tanpa log masuk',
    btn_download_pdf_direct: 'Muat Turun Laporan (PDF)',
    btn_full_history: 'Sejarah Transaksi Penuh',
    btn_export_csv: 'Eksport Transaksi ke CSV',
    btn_clear_all: 'Kosongkan Semua Baki',
    modal_tx_type_label: 'Jenis Transaksi',
    modal_tx_cat_label: 'Kategori',
    modal_tx_add_custom_cat: 'Tambah Kategori Sendiri',
    modal_tx_amount_label: 'Jumlah',
    modal_tx_date_label: 'Tarikh',
    modal_tx_wallet_label: 'Dompet',
    modal_tx_no_wallet: 'Tiada Dompet',
    modal_tx_note_label: 'Nota',
    modal_tx_optional: '(Pilihan)',
    modal_tx_note_placeholder: 'Tulis nota ringkas...',
    btn_cancel: 'Batal',
    btn_save_tx: 'Simpan Transaksi',
    btn_update_tx: 'Kemas Kini Transaksi',
    modal_cat_title: 'Tambah Kategori Baharu',
    modal_cat_group_label: 'Kumpulan Pos',
    modal_cat_name_label: 'Nama Kategori Baharu',
    modal_cat_name_placeholder: 'Cth: Simpanan Rumah / Percutian...',
    btn_add: 'Tambah',
    modal_wallet_bal_title: 'Tetapkan Baki',
    modal_wallet_bal_label: 'Baki Semasa',
    btn_save_balance: 'Simpan Baki',
    modal_new_wallet_title: 'Tambah Dompet Baharu',
    modal_new_wallet_type: 'Jenis Dompet',
    modal_new_wallet_name: 'Nama Dompet',
    modal_new_wallet_placeholder: 'Taip nama Bank / E-Dompet / Tunai...',
    modal_new_wallet_initial: 'Baki Awal',
    btn_save_wallet: 'Simpan Dompet',
    modal_budget_period: 'Tempoh:',
    modal_budget_note: 'Pendapatan dan Dana Kecemasan adalah fleksibel dan tidak memerlukan sasaran bajet bulanan.',
    btn_save_budget: 'Simpan Bajet',
    modal_google_title: 'Kesan Akaun Google Peranti',
    modal_google_sub: 'Log masuk untuk menyambungkan Sandaran Transaksi ke Google Drive',
    modal_google_scanning_title: 'Mengesan Akaun Google pada Peranti Ini...',
    modal_google_scanning_sub: 'Memeriksa sesi akaun Google yang disimpan pada peranti anda',
    modal_google_detected_label: 'Akaun Google Dikesan pada Peranti',
    modal_google_pick_btn: 'Pilih & Log Masuk',
    modal_google_info: 'Log masuk diperlukan dahulu. Selepas log masuk dan menekan "Sandarkan Transaksi Anda", ia akan berjalan secara automatik di latar belakang ke Google Drive.',
    modal_google_name_label: 'Nama Akaun Google Peranti',
    modal_google_email_label: 'E-mel Google (Gmail) pada Peranti',
    btn_login_connect_device: 'Log Masuk & Sambung Peranti',
    modal_sec_title: 'Tetapkan Kata Laluan',
    modal_sec_sub: 'Pilih kaedah penguncian aplikasi',
    sec_pin_setup_title: 'Cipta 6 Digit PIN Keselamatan',
    sec_pin_setup_sub: 'Tekan nombor di bawah untuk menetapkan PIN baharu',
    btn_save_pin: 'Simpan & Aktifkan PIN',
    sec_pattern_setup_title: 'Lukis Corak Kunci (Min. 4 Titik)',
    sec_pattern_setup_sub: 'Sambungkan titik pada grid 3x3 di bawah',
    btn_reset_pattern: 'Ulang Corak',
    btn_save_pattern: 'Simpan Corak',
    sec_fp_setup_title: 'Cap Jari Peranti (Biometrik)',
    sec_fp_setup_sub: 'Gunakan penderia cap jari perkakasan peranti anda untuk mengunci aplikasi.',
    sec_fp_click_scan: 'Ketik penderia untuk mengesahkan cap jari peranti',
    lock_screen_title: 'FinanceTracker Dikunci',
    lock_screen_pin_prompt: 'Masukkan 6 digit PIN keselamatan anda',
    lock_screen_pattern_prompt: 'Lukis Corak Kunci anda pada grid 3x3 di bawah',
    lock_screen_fp_prompt: 'Sahkan penderia cap jari peranti anda untuk membuka kunci',
    lock_screen_forgot: 'Lupa Kata Laluan? Reset Kunci'
  },
  ja: {
    nav_dashboard: 'ダッシュボード',
    nav_wallets: 'ウォレット',
    nav_income: '収入',
    nav_expense: '支出',
    nav_savings: '貯蓄',
    nav_history: '取引履歴',
    nav_settings: '設定',
    nav_home_mobile: 'ホーム',
    btn_budget_short: '予算',
    btn_add_tx: '取引を追加',
    btn_edit_tx: '取引を編集',
    btn_monthly_budget: '月間予算',
    open_month_period: '利用可能な月',
    all_months_1_year: 'すべての月 (1年間)',
    card_total_income: '総収入',
    card_total_expense: '総支出',
    card_total_savings: '総貯蓄',
    card_total_balance: '残高合計',
    btn_open_wallet: 'ウォレットを開く',
    sec_analytics: 'ビジュアル分析',
    chart_top_spending: '支出トップ',
    chart_top_spending_sub: '支出カテゴリー',
    chart_savings_dist: '貯蓄配分',
    chart_savings_dist_sub: '貯蓄の内訳',
    chart_actual_vs_budget: '実績 vs 予算',
    chart_actual_vs_budget_sub: '月別の支出と予算',
    chart_actual_label: '実績',
    chart_budget_label: '予算',
    chart_empty: 'データなし',
    sec_recent_tx: '最近の取引',
    btn_view_all: 'すべて表示',
    empty_tx_period: 'この期間の取引はまだありません',
    wallet_total_title: 'ウォレット総残高',
    wallet_hero_desc: '銀行口座、電子マネー、現金の残高を一元管理します。',
    btn_add_wallet: 'ウォレット追加',
    wallet_cat_bank: '銀行',
    wallet_cat_cash: '現金',
    wallet_cat_ewallet: '電子マネー',
    wallet_account_unit: '口座',
    wallet_list_title: '資金保管リスト',
    wallet_list_desc: 'カテゴリーを選択して各ウォレットの残高を表示します。',
    filter_all: 'すべて',
    wallet_empty_all_title: 'ウォレットがまだありません',
    wallet_empty_all_desc: '銀行口座、電子マネー、または現金を追加して残高と取引を自動記録しましょう。',
    wallet_empty_bank_title: '銀行口座がありません',
    wallet_empty_bank_desc: '銀行口座を追加して残高を管理します。',
    wallet_empty_cash_title: '現金ウォレットがありません',
    wallet_empty_cash_desc: '現金ウォレットを追加して日々の現金支出を管理します。',
    wallet_empty_ewallet_title: '電子マネーがありません',
    wallet_empty_ewallet_desc: '電子マネーを追加して残高と決済を管理します。',
    wallet_btn_set_balance: '残高設定',
    wallet_stored_balance: '現在の残高',
    wallet_in: '入金',
    wallet_out: '出金',
    wallet_share: '残高割合',
    income_tab_title: '収入内訳 (Income)',
    income_tab_sub: '総収入額',
    btn_new_source: '+ 新規収入源',
    btn_add_income: '収入を追加',
    th_income_source: '収入源',
    th_income_share: '割合 (%)',
    th_income_bar: '収入比率バー',
    th_income_total: '収入合計',
    income_source_sub: '収入カテゴリー',
    expense_tab_title: '支出内訳 (Expenses)',
    expense_tab_from_budget: '予算比',
    btn_new_category: '+ 新規カテゴリー',
    btn_add_expense: '支出を追加',
    savings_tab_title: '貯蓄内訳 (Savings)',
    savings_tab_target: '目標額:',
    btn_add_savings: '貯蓄を追加',
    th_category: 'カテゴリー',
    th_tracked: '実績',
    th_budget: '予算',
    th_usage_pct: '使用率 %',
    th_visual_bar: '進捗バー',
    th_budget_left: '予算残高',
    th_excess: '超過額',
    badge_flexible_no_min: '自由積立・上限なし',
    label_no_min: '目標なし',
    badge_ready_use: '利用可能',
    label_emergency_balance: '緊急資金残高',
    label_emergency_sub: '緊急時にいつでも利用可能',
    badge_overbudget: '予算超過 (>100%)',
    history_title: '取引履歴',
    tx_unit: '件',
    btn_reset_short: 'リセット',
    search_placeholder: 'カテゴリー、ウォレット、メモを検索...',
    all_types: 'すべての種類',
    th_date: '日付',
    th_type: '種類',
    th_cat_note: 'カテゴリー・メモ',
    th_wallet: 'ウォレット',
    th_amount: '金額',
    th_action: '操作',
    settings_appearance_title: '外観・通貨・言語設定',
    settings_appearance_desc: 'ダーク/ライトモード、通貨形式、表示言語を設定します',
    settings_theme_label: '表示モード (Dual Mode)',
    theme_dark: 'ダーク',
    theme_light: 'ライト',
    settings_currency_label: '通貨フォーマット',
    settings_language_label: '表示言語',
    settings_security_title: 'パスワード・セキュリティ',
    settings_security_desc: 'PIN、パターン、または端末の指紋認証でロック',
    sec_status_inactive: '無効',
    sec_status_active: '有効',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'パターン',
    sec_method_fingerprint: '指紋認証',
    sec_active_method_label: '有効な方式:',
    btn_lock_now: '今すぐロック',
    btn_change_pass: '変更',
    btn_disable_pass: '解除',
    fp_not_available_device: 'この端末では指紋センサーを利用できません',
    fp_not_supported_toast: 'この端末には対応する指紋センサーがないため、使用できません。',
    settings_backup_title: 'Googleドライブ自動バックアップ',
    settings_backup_desc: 'バックグラウンドで取引データを自動保存し、機種変更時もデータを引き継ぎます',
    badge_not_logged_in: '未ログイン',
    badge_auto_sync: '自動同期オン',
    badge_connected: '接続済み',
    backup_device_sync_title: '端末のGoogleアカウント同期',
    backup_device_sync_desc: '下の「取引をバックアップする」をクリックすると、端末のGoogleアカウントを自動検出してログインします。',
    backup_detected_on: '検出端末:',
    btn_switch_account: 'アカウント切替',
    btn_logout: 'ログアウト',
    backup_auto_bg_label: 'バックグラウンド自動バックアップ (Googleドライブ)',
    bg_sync_connecting: 'バックグラウンドでGoogleドライブに接続中...',
    bg_sync_uploading: '取引データをGoogleドライブにバックアップ中...',
    bg_sync_done: 'Googleドライブと自動同期しました！',
    btn_backup_transactions: '取引をバックアップする',
    btn_restore_transactions: 'バックアップを復元',
    btn_import_backup: 'バックアップ読込',
    backup_history_title: 'バックアップ履歴',
    backup_unit: '件',
    backup_history_empty: 'Googleドライブにバックアップ履歴はまだありません。',
    settings_report_title: 'PDFレポート＆データ管理',
    settings_report_desc: 'ログイン不要でPDFレポートを即座にダウンロード',
    btn_download_pdf_direct: 'レポートをPDFでダウンロード',
    btn_full_history: '全取引履歴を表示',
    btn_export_csv: 'CSVにエクスポート',
    btn_clear_all: 'すべてのデータをリセット',
    modal_tx_type_label: '取引の種類',
    modal_tx_cat_label: 'カテゴリー',
    modal_tx_add_custom_cat: 'カスタム追加',
    modal_tx_amount_label: '金額',
    modal_tx_date_label: '日付',
    modal_tx_wallet_label: 'ウォレット',
    modal_tx_no_wallet: 'ウォレットなし',
    modal_tx_note_label: 'メモ',
    modal_tx_optional: '(任意)',
    modal_tx_note_placeholder: '簡単なメモを入力...',
    btn_cancel: 'キャンセル',
    btn_save_tx: '取引を保存',
    btn_update_tx: '取引を更新',
    modal_cat_title: '新規カテゴリー追加',
    modal_cat_group_label: 'グループ',
    modal_cat_name_label: 'カテゴリー名',
    modal_cat_name_placeholder: '例：住宅貯蓄 / 旅行...',
    btn_add: '追加する',
    modal_wallet_bal_title: '残高を設定',
    modal_wallet_bal_label: '現在の残高',
    btn_save_balance: '残高を保存',
    modal_new_wallet_title: '新規ウォレット追加',
    modal_new_wallet_type: 'ウォレット種類',
    modal_new_wallet_name: 'ウォレット名',
    modal_new_wallet_placeholder: '銀行名 / 電子マネー / 現金を入力...',
    modal_new_wallet_initial: '初期残高',
    btn_save_wallet: 'ウォレットを保存',
    modal_budget_period: '期間:',
    modal_budget_note: '収入と緊急資金は柔軟な項目のため、月間目標予算の設定は不要です。',
    btn_save_budget: '予算を保存',
    modal_google_title: '端末のGoogleアカウント検出',
    modal_google_sub: 'Googleドライブへのバックアップ連携のためログインしてください',
    modal_google_scanning_title: 'この端末のGoogleアカウントを検出中...',
    modal_google_scanning_sub: '端末に保存されているGoogleアカウントを確認しています',
    modal_google_detected_label: '検出されたGoogleアカウント',
    modal_google_pick_btn: '選択してログイン',
    modal_google_info: '最初にログインが必要です。ログイン後に「取引をバックアップする」を押すと、バックグラウンドでGoogleドライブに自動保存されます。',
    modal_google_name_label: 'Googleアカウント名',
    modal_google_email_label: 'Gmailアドレス',
    btn_login_connect_device: 'ログインして接続',
    modal_sec_title: 'パスワード設定',
    modal_sec_sub: 'アプリのロック方式を選択',
    sec_pin_setup_title: '6桁のPINコードを作成',
    sec_pin_setup_sub: '下の数字キーを押してPINを設定してください',
    btn_save_pin: 'PINを保存して有効化',
    sec_pattern_setup_title: 'パターンを描画 (4点以上)',
    sec_pattern_setup_sub: '3x3のドットを繋いでパターンを作成してください',
    btn_reset_pattern: 'やり直す',
    btn_save_pattern: 'パターンを保存',
    sec_fp_setup_title: '端末の指紋認証 (生体認証)',
    sec_fp_setup_sub: 'お使いの端末の指紋センサーを使用してアプリを保護します。',
    sec_fp_click_scan: 'センサーをタップして端末の指紋を認証',
    lock_screen_title: 'FinanceTracker ロック中',
    lock_screen_pin_prompt: '6桁のPINコードを入力してください',
    lock_screen_pattern_prompt: '3x3グリッドにロック解除パターンを描いてください',
    lock_screen_fp_prompt: '端末の指紋センサーで認証してロックを解除してください',
    lock_screen_forgot: 'パスワードを忘れた場合（リセット）'
  },
  ko: {
    nav_dashboard: '대시보드',
    nav_wallets: '지갑',
    nav_income: '수입',
    nav_expense: '지출',
    nav_savings: '저축',
    nav_history: '거래 내역',
    nav_settings: '설정',
    nav_home_mobile: '홈',
    btn_budget_short: '예산',
    btn_add_tx: '거래 추가',
    btn_edit_tx: '거래 수정',
    btn_monthly_budget: '월간 예산',
    open_month_period: '열린 월 기간',
    all_months_1_year: '전체 월 (1년)',
    card_total_income: '총 수입',
    card_total_expense: '총 지출',
    card_total_savings: '총 저축',
    card_total_balance: '총 잔액',
    btn_open_wallet: '지갑 열기',
    sec_analytics: '시각 분석',
    chart_top_spending: '주요 지출',
    chart_top_spending_sub: '지출 카테고리',
    chart_savings_dist: '저축 분포',
    chart_savings_dist_sub: '저축 할당',
    chart_actual_vs_budget: '실제 지출 vs 예산',
    chart_actual_vs_budget_sub: '월별 지출 및 예산 비교',
    chart_actual_label: '실제',
    chart_budget_label: '예산',
    chart_empty: '비어 있음',
    sec_recent_tx: '최근 거래',
    btn_view_all: '전체 보기',
    empty_tx_period: '이 기간에 기록된 거래가 없습니다',
    wallet_total_title: '총 지갑 잔액',
    wallet_hero_desc: '은행 계좌, 전자지갑 및 현금 잔액을 한곳에서 관리하세요.',
    btn_add_wallet: '지갑 추가',
    wallet_cat_bank: '은행',
    wallet_cat_cash: '현금',
    wallet_cat_ewallet: '전자지갑',
    wallet_account_unit: '계좌',
    wallet_list_title: '자산 보관 목록',
    wallet_list_desc: '카테고리를 선택하여 지갑별 상세 잔액을 확인하세요.',
    filter_all: '전체',
    wallet_empty_all_title: '저장된 지갑이 없습니다',
    wallet_empty_all_desc: '은행 계좌, 전자지갑 또는 현금을 추가하여 잔액과 내역을 자동으로 관리하세요.',
    wallet_empty_bank_title: '등록된 은행 계좌 없음',
    wallet_empty_bank_desc: '은행 계좌를 추가하여 잔액을 관리하세요.',
    wallet_empty_cash_title: '등록된 현금 지갑 없음',
    wallet_empty_cash_desc: '현금 지갑을 추가하여 일일 현금 지출을 기록하세요.',
    wallet_empty_ewallet_title: '등록된 전자지갑 없음',
    wallet_empty_ewallet_desc: '전자지갑을 추가하여 잔액을 확인하세요.',
    wallet_btn_set_balance: '잔액 설정',
    wallet_stored_balance: '보유 잔액',
    wallet_in: '입금',
    wallet_out: '출금',
    wallet_share: '잔액 비율',
    income_tab_title: '수입 내역 (Income)',
    income_tab_sub: '총 유입 자금',
    btn_new_source: '+ 새 수입원',
    btn_add_income: '수입 추가',
    th_income_source: '수입원',
    th_income_share: '비중 (%)',
    th_income_bar: '수입 비율',
    th_income_total: '총 수입',
    income_source_sub: '수입원 항목',
    expense_tab_title: '지출 내역 (Expenses)',
    expense_tab_from_budget: '예산 대비',
    btn_new_category: '+ 새 카테고리',
    btn_add_expense: '지출 추가',
    savings_tab_title: '저축 내역 (Savings)',
    savings_tab_target: '목표 예산:',
    btn_add_savings: '저축 추가',
    th_category: '카테고리',
    th_tracked: '사용액',
    th_budget: '예산',
    th_usage_pct: '사용률 %',
    th_visual_bar: '진행 상태',
    th_budget_left: '남은 예산',
    th_excess: '초과액',
    badge_flexible_no_min: '자유 적립 • 최소 금액 없음',
    label_no_min: '제한 없음',
    badge_ready_use: '사용 가능',
    label_emergency_balance: '비상금 잔액',
    label_emergency_sub: '비상시 언제든 사용 가능',
    badge_overbudget: '예산 초과 (>100%)',
    history_title: '거래 내역',
    tx_unit: '건',
    btn_reset_short: '초기화',
    search_placeholder: '카테고리, 지갑, 메모 검색...',
    all_types: '모든 유형',
    th_date: '날짜',
    th_type: '유형',
    th_cat_note: '카테고리 및 메모',
    th_wallet: '지갑',
    th_amount: '금액',
    th_action: '작업',
    settings_appearance_title: '화면, 통화 및 언어',
    settings_appearance_desc: '다크/라이트 모드, 통화 형식 및 언어를 설정합니다',
    settings_theme_label: '화면 모드 (Dual Mode)',
    theme_dark: '다크',
    theme_light: '라이트',
    settings_currency_label: '통화 형식',
    settings_language_label: '언어 선택',
    settings_security_title: '비밀번호 및 보안',
    settings_security_desc: 'PIN, 패턴 또는 기기 지문 인식으로 앱 잠금',
    sec_status_inactive: '비활성',
    sec_status_active: '활성',
    sec_method_pin: 'PIN',
    sec_method_pattern: '패턴',
    sec_method_fingerprint: '지문 인식',
    sec_active_method_label: '활성 방식:',
    btn_lock_now: '지금 잠금',
    btn_change_pass: '변경',
    btn_disable_pass: '잠금 해제',
    fp_not_available_device: '이 기기에서는 지문 센서를 사용할 수 없습니다',
    fp_not_supported_toast: '이 기기에는 지원되는 지문 센서가 없어 사용할 수 없습니다.',
    settings_backup_title: 'Google 드라이브 자동 백업',
    settings_backup_desc: '백그라운드에서 거래 내역을 Google 드라이브에 백업하여 기기 변경 시 복원합니다',
    badge_not_logged_in: '미로그인',
    badge_auto_sync: '자동 동기화 켜짐',
    badge_connected: '연결됨',
    backup_device_sync_title: '기기 Google 계정 동기화',
    backup_device_sync_desc: '아래 "거래 내역 백업하기"를 클릭하면 기기의 Google 계정을 자동 감지하여 먼저 로그인합니다.',
    backup_detected_on: '감지된 기기:',
    btn_switch_account: '계정 변경',
    btn_logout: '로그아웃',
    backup_auto_bg_label: '백그라운드 자동 백업 (Google 드라이브)',
    bg_sync_connecting: '백그라운드에서 Google 드라이브에 연결 중...',
    bg_sync_uploading: '거래 및 지갑 데이터를 Google 드라이브에 백업 중...',
    bg_sync_done: 'Google 드라이브와 자동 동기화되었습니다!',
    btn_backup_transactions: '거래 내역 백업하기',
    btn_restore_transactions: '백업 복원',
    btn_import_backup: '백업 파일 가져오기',
    backup_history_title: '거래 백업 기록',
    backup_unit: '개',
    backup_history_empty: 'Google 드라이브에 백업된 거래 파일이 없습니다.',
    settings_report_title: 'PDF 보고서 및 데이터 관리',
    settings_report_desc: '로그인 없이 즉시 PDF 보고서 다운로드 및 데이터 관리',
    btn_download_pdf_direct: '보고서 다운로드 (PDF)',
    btn_full_history: '전체 거래 내역',
    btn_export_csv: 'CSV로 내보내기',
    btn_clear_all: '모든 금액 초기화',
    modal_tx_type_label: '거래 유형',
    modal_tx_cat_label: '카테고리',
    modal_tx_add_custom_cat: '직접 카테고리 추가',
    modal_tx_amount_label: '금액',
    modal_tx_date_label: '날짜',
    modal_tx_wallet_label: '지갑',
    modal_tx_no_wallet: '지갑 없음',
    modal_tx_note_label: '메모',
    modal_tx_optional: '(선택)',
    modal_tx_note_placeholder: '간단한 메모 입력...',
    btn_cancel: '취소',
    btn_save_tx: '거래 저장',
    btn_update_tx: '거래 업데이트',
    modal_cat_title: '새 카테고리 추가',
    modal_cat_group_label: '항목 그룹',
    modal_cat_name_label: '새 카테고리 이름',
    modal_cat_name_placeholder: '예: 주택 저축 / 여행...',
    btn_add: '추가',
    modal_wallet_bal_title: '잔액 설정',
    modal_wallet_bal_label: '현재 잔액',
    btn_save_balance: '잔액 저장',
    modal_new_wallet_title: '새 지갑 추가',
    modal_new_wallet_type: '지갑 유형',
    modal_new_wallet_name: '지갑 이름',
    modal_new_wallet_placeholder: '은행 / 전자지갑 / 현금 이름 입력...',
    modal_new_wallet_initial: '초기 잔액',
    btn_save_wallet: '지갑 저장',
    modal_budget_period: '기간:',
    modal_budget_note: '수입 및 비상금은 유연한 항목이므로 월간 목표 예산이 필요하지 않습니다.',
    btn_save_budget: '예산 저장',
    modal_google_title: '기기 Google 계정 감지',
    modal_google_sub: 'Google 드라이브에 거래 백업을 연결하려면 로그인하세요',
    modal_google_scanning_title: '이 기기의 Google 계정 감지 중...',
    modal_google_scanning_sub: '기기에 저장된 Google 계정 세션을 확인하고 있습니다',
    modal_google_detected_label: '기기에서 감지된 Google 계정',
    modal_google_pick_btn: '선택 및 로그인',
    modal_google_info: '먼저 로그인이 필요합니다. 로그인 후 "거래 내역 백업하기"를 누르면 백그라운드에서 Google 드라이브와 자동 동기화됩니다.',
    modal_google_name_label: 'Google 계정 이름',
    modal_google_email_label: 'Google 이메일 (Gmail)',
    btn_login_connect_device: '로그인 및 기기 연결',
    modal_sec_title: '비밀번호 설정',
    modal_sec_sub: '앱 잠금 방식을 선택하세요',
    sec_pin_setup_title: '6자리 보안 PIN 생성',
    sec_pin_setup_sub: '아래 숫자를 눌러 새 PIN을 설정하세요',
    btn_save_pin: 'PIN 저장 및 활성화',
    sec_pattern_setup_title: '패턴 그리기 (최소 4개 점)',
    sec_pattern_setup_sub: '아래 3x3 그리드의 점들을 연결하세요',
    btn_reset_pattern: '패턴 초기화',
    btn_save_pattern: '패턴 저장',
    sec_fp_setup_title: '기기 지문 인식 (생체 인증)',
    sec_fp_setup_sub: '기기의 내장 지문 센서를 사용하여 앱을 잠급니다.',
    sec_fp_click_scan: '센서를 탭하여 기기 지문을 스캔하세요',
    lock_screen_title: 'FinanceTracker 잠김',
    lock_screen_pin_prompt: '6자리 보안 PIN을 입력하세요',
    lock_screen_pattern_prompt: '아래 3x3 그리드에 잠금 해제 패턴을 그리세요',
    lock_screen_fp_prompt: '잠금을 해제하려면 기기 지문 센서를 인증하세요',
    lock_screen_forgot: '비밀번호 분실? 잠금 초기화'
  },
  zh: {
    nav_dashboard: '仪表盘',
    nav_wallets: '钱包',
    nav_income: '收入',
    nav_expense: '支出',
    nav_savings: '储蓄',
    nav_history: '交易记录',
    nav_settings: '设置',
    nav_home_mobile: '首页',
    btn_budget_short: '预算',
    btn_add_tx: '添加交易',
    btn_edit_tx: '编辑交易',
    btn_monthly_budget: '月度预算',
    open_month_period: '可用月份',
    all_months_1_year: '所有月份 (全年)',
    card_total_income: '总收入',
    card_total_expense: '总支出',
    card_total_savings: '总储蓄',
    card_total_balance: '总结余',
    btn_open_wallet: '打开钱包',
    sec_analytics: '可视化分析',
    chart_top_spending: '最高支出',
    chart_top_spending_sub: '支出类别占比',
    chart_savings_dist: '储蓄分布',
    chart_savings_dist_sub: '储蓄资金分配',
    chart_actual_vs_budget: '实际支出 vs 预算',
    chart_actual_vs_budget_sub: '每月支出与预算对比',
    chart_actual_label: '实际',
    chart_budget_label: '预算',
    chart_empty: '暂无数据',
    sec_recent_tx: '最近交易',
    btn_view_all: '查看全部',
    empty_tx_period: '本周期内暂无交易记录',
    wallet_total_title: '钱包总余额',
    wallet_hero_desc: '在一处监控和管理您的银行账户、电子钱包和现金余额。',
    btn_add_wallet: '添加钱包',
    wallet_cat_bank: '银行卡',
    wallet_cat_cash: '现金',
    wallet_cat_ewallet: '电子钱包',
    wallet_account_unit: '个账户',
    wallet_list_title: '资金账户列表',
    wallet_list_desc: '选择类别以查看各个钱包的详细余额。',
    filter_all: '全部',
    wallet_empty_all_title: '暂未添加任何钱包',
    wallet_empty_all_desc: '添加您的银行账户、电子钱包或现金，以便自动记录所有余额和交易变动。',
    wallet_empty_bank_title: '暂无银行账户',
    wallet_empty_bank_desc: '添加您的银行卡以监控储蓄和交易。',
    wallet_empty_cash_title: '暂无现金钱包',
    wallet_empty_cash_desc: '添加现金钱包以记录日常现金支出。',
    wallet_empty_ewallet_title: '暂无电子钱包',
    wallet_empty_ewallet_desc: '添加电子钱包以监控日常支付余额。',
    wallet_btn_set_balance: '设置余额',
    wallet_stored_balance: '当前余额',
    wallet_in: '流入',
    wallet_out: '流出',
    wallet_share: '余额占比',
    income_tab_title: '收入明细 (Income)',
    income_tab_sub: '总流入资金',
    btn_new_source: '+ 新增来源',
    btn_add_income: '添加收入',
    th_income_source: '资金来源',
    th_income_share: '占比 (%)',
    th_income_bar: '资金比例',
    th_income_total: '总流入',
    income_source_sub: '收入来源',
    expense_tab_title: '支出明细 (Expenses)',
    expense_tab_from_budget: '预算总额',
    btn_new_category: '+ 新增类别',
    btn_add_expense: '添加支出',
    savings_tab_title: '储蓄明细 (Savings)',
    savings_tab_target: '计划目标:',
    btn_add_savings: '添加储蓄',
    th_category: '类别',
    th_tracked: '已记录',
    th_budget: '预算',
    th_usage_pct: '使用率 %',
    th_visual_bar: '进度条',
    th_budget_left: '剩余预算',
    th_excess: '超支',
    badge_flexible_no_min: '灵活存取 • 无最低限制',
    label_no_min: '无限制',
    badge_ready_use: '随时可用',
    label_emergency_balance: '紧急备用金余额',
    label_emergency_sub: '紧急情况下可随时动用',
    badge_overbudget: '超出预算 (>100%)',
    history_title: '交易历史记录',
    tx_unit: '笔交易',
    btn_reset_short: '重置',
    search_placeholder: '搜索类别、钱包、备注...',
    all_types: '所有类型',
    th_date: '日期',
    th_type: '类型',
    th_cat_note: '类别与备注',
    th_wallet: '钱包',
    th_amount: '金额',
    th_action: '操作',
    settings_appearance_title: '外观、货币与语言',
    settings_appearance_desc: '设置深色/浅色双模式、货币格式及应用语言',
    settings_theme_label: '显示模式 (Dual Mode)',
    theme_dark: '深色',
    theme_light: '浅色',
    settings_currency_label: '货币格式',
    settings_language_label: '语言选择',
    settings_security_title: '密码与安全锁',
    settings_security_desc: '使用 PIN 码、图案或设备指纹锁定应用',
    sec_status_inactive: '未启用',
    sec_status_active: '已启用',
    sec_method_pin: 'PIN',
    sec_method_pattern: '图案',
    sec_method_fingerprint: '指纹',
    sec_active_method_label: '当前方式:',
    btn_lock_now: '立即锁定',
    btn_change_pass: '修改密码',
    btn_disable_pass: '关闭密码',
    fp_not_available_device: '此设备不支持指纹传感器',
    fp_not_supported_toast: '此设备没有受支持的指纹传感器，无法使用此功能。',
    settings_backup_title: 'Google 云端硬盘自动备份',
    settings_backup_desc: '在后台自动将交易备份至 Google Drive，更换设备无需从零开始',
    badge_not_logged_in: '未登录',
    badge_auto_sync: '自动同步已开启',
    badge_connected: '已连接',
    backup_device_sync_title: '设备 Google 账号同步',
    backup_device_sync_desc: '点击下方“备份您的交易记录”，系统将自动检测此设备上的 Google 账号并要求先登录。',
    backup_detected_on: '检测于',
    btn_switch_account: '切换账号',
    btn_logout: '退出',
    backup_auto_bg_label: '后台自动备份 (Google Drive)',
    bg_sync_connecting: '正在后台连接至 Google Drive...',
    bg_sync_uploading: '正在将交易和钱包数据备份至 Google Drive...',
    bg_sync_done: '已与 Google Drive 自动同步！',
    btn_backup_transactions: '备份您的交易记录',
    btn_restore_transactions: '恢复备份数据',
    btn_import_backup: '导入备份文件',
    backup_history_title: '交易备份历史',
    backup_unit: '个备份',
    backup_history_empty: 'Google Drive 中暂无交易备份文件。',
    settings_report_title: 'PDF 报表与数据管理',
    settings_report_desc: '无需登录即可直接自动下载 PDF 财务报表',
    btn_download_pdf_direct: '下载财务报表 (PDF)',
    btn_full_history: '完整交易记录',
    btn_export_csv: '导出交易至 CSV',
    btn_clear_all: '清空所有金额数据',
    modal_tx_type_label: '交易类型',
    modal_tx_cat_label: '类别',
    modal_tx_add_custom_cat: '添加自定义类别',
    modal_tx_amount_label: '金额',
    modal_tx_date_label: '日期',
    modal_tx_wallet_label: '钱包',
    modal_tx_no_wallet: '无钱包',
    modal_tx_note_label: '备注',
    modal_tx_optional: '(选填)',
    modal_tx_note_placeholder: '输入简短说明...',
    btn_cancel: '取消',
    btn_save_tx: '保存交易',
    btn_update_tx: '更新交易',
    modal_cat_title: '添加新类别',
    modal_cat_group_label: '所属分组',
    modal_cat_name_label: '新类别名称',
    modal_cat_name_placeholder: '例如：购房储蓄 / 旅行...',
    btn_add: '添加',
    modal_wallet_bal_title: '设置余额',
    modal_wallet_bal_label: '当前余额',
    btn_save_balance: '保存余额',
    modal_new_wallet_title: '添加新钱包',
    modal_new_wallet_type: '钱包类型',
    modal_new_wallet_name: '钱包名称',
    modal_new_wallet_placeholder: '输入银行 / 电子钱包 / 现金名称...',
    modal_new_wallet_initial: '初始余额',
    btn_save_wallet: '保存钱包',
    modal_budget_period: '周期:',
    modal_budget_note: '收入和紧急备用金属于灵活项目，无需设置月度目标预算。',
    btn_save_budget: '保存预算',
    modal_google_title: '检测设备 Google 账号',
    modal_google_sub: '登录以将交易备份连接至 Google Drive',
    modal_google_scanning_title: '正在检测此设备上的 Google 账号...',
    modal_google_scanning_sub: '正在检查您设备上保存的 Google 账号会话',
    modal_google_detected_label: '设备上检测到的 Google 账号',
    modal_google_pick_btn: '选择并登录',
    modal_google_info: '必须先登录。登录并点击“备份您的交易记录”后，将在后台自动同步至 Google Drive。',
    modal_google_name_label: '设备 Google 账号名称',
    modal_google_email_label: '设备 Google 邮箱 (Gmail)',
    btn_login_connect_device: '登录并连接设备',
    modal_sec_title: '设置密码锁',
    modal_sec_sub: '选择应用锁定方式',
    sec_pin_setup_title: '创建 6 位数字 PIN 码',
    sec_pin_setup_sub: '点击下方数字设置新 PIN 码',
    btn_save_pin: '保存并启用 PIN',
    sec_pattern_setup_title: '绘制解锁图案 (至少 4 个点)',
    sec_pattern_setup_sub: '连接下方 3x3 网格中的点',
    btn_reset_pattern: '重绘图案',
    btn_save_pattern: '保存图案',
    sec_fp_setup_title: '设备指纹解锁 (生物识别)',
    sec_fp_setup_sub: '使用您设备自带的硬件指纹传感器锁定应用。',
    sec_fp_click_scan: '点击传感器验证设备指纹',
    lock_screen_title: 'FinanceTracker 已锁定',
    lock_screen_pin_prompt: '请输入您的 6 位数字安全 PIN 码',
    lock_screen_pattern_prompt: '请在下方 3x3 网格绘制解锁图案',
    lock_screen_fp_prompt: '请验证设备指纹传感器以解锁',
    lock_screen_forgot: '忘记密码？重置锁定'
  },
  ar: {
    nav_dashboard: 'لوحة التحكم',
    nav_wallets: 'المحفظة',
    nav_income: 'الدخل',
    nav_expense: 'المصروفات',
    nav_savings: 'المدخرات',
    nav_history: 'سجل المعاملات',
    nav_settings: 'الإعدادات',
    nav_home_mobile: 'الرئيسية',
    btn_budget_short: 'الميزانية',
    btn_add_tx: 'إضافة معاملة',
    btn_edit_tx: 'تعديل المعاملة',
    btn_monthly_budget: 'الميزانية الشهرية',
    open_month_period: 'الأشهر المتاحة',
    all_months_1_year: 'جميع الأشهر (سنة كاملة)',
    card_total_income: 'إجمالي الدخل',
    card_total_expense: 'إجمالي المصروفات',
    card_total_savings: 'إجمالي المدخرات',
    card_total_balance: 'الرصيد الصافي',
    btn_open_wallet: 'فتح المحفظة',
    sec_analytics: 'التحليلات المرئية',
    chart_top_spending: 'أعلى المصروفات',
    chart_top_spending_sub: 'فئات الإنفاق',
    chart_savings_dist: 'توزيع المدخرات',
    chart_savings_dist_sub: 'تخصيص التوفير',
    chart_actual_vs_budget: 'الفعلي مقابل الميزانية',
    chart_actual_vs_budget_sub: 'المصروفات الشهرية مقابل الميزانية',
    chart_actual_label: 'الفعلي',
    chart_budget_label: 'الميزانية',
    chart_empty: 'فارغ',
    sec_recent_tx: 'أحدث المعاملات',
    btn_view_all: 'عرض الكل',
    empty_tx_period: 'لا توجد معاملات مسجلة في هذه الفترة',
    wallet_total_title: 'إجمالي رصيد المحفظة',
    wallet_hero_desc: 'راقب وأدر أرصدة الحسابات البنكية والمحافظ الرقمية والنقدية في مكان واحد.',
    btn_add_wallet: 'إضافة محفظة',
    wallet_cat_bank: 'بنك',
    wallet_cat_cash: 'نقدي',
    wallet_cat_ewallet: 'محفظة رقمية',
    wallet_account_unit: 'حساب',
    wallet_list_title: 'قائمة حفظ الأموال',
    wallet_list_desc: 'اختر فئة لعرض تفاصيل رصيد كل محفظة.',
    filter_all: 'الكل',
    wallet_empty_all_title: 'لا توجد محافظ محفوظة بعد',
    wallet_empty_all_desc: 'أضف حسابك البنكي أو محفظتك الرقمية أو النقدية لتسجيل الأرصدة تلقائياً.',
    wallet_empty_bank_title: 'لا توجد حسابات بنكية',
    wallet_empty_bank_desc: 'أضف حسابك البنكي لمتابعة الرصيد.',
    wallet_empty_cash_title: 'لا توجد محفظة نقدية',
    wallet_empty_cash_desc: 'أضف محفظة نقدية لتتبع المصروفات اليومية.',
    wallet_empty_ewallet_title: 'لا توجد محفظة رقمية',
    wallet_empty_ewallet_desc: 'أضف محفظتك الرقمية لمتابعة المدفوعات.',
    wallet_btn_set_balance: 'تعديل الرصيد',
    wallet_stored_balance: 'الرصيد المحفوظ',
    wallet_in: 'وارد',
    wallet_out: 'صادر',
    wallet_share: 'نسبة الرصيد',
    income_tab_title: 'تفاصيل الدخل (Income)',
    income_tab_sub: 'إجمالي الأموال الواردة',
    btn_new_source: '+ مصدر جديد',
    btn_add_income: 'إضافة دخل',
    th_income_source: 'مصدر الدخل',
    th_income_share: 'المساهمة (%)',
    th_income_bar: 'نسبة الدخل',
    th_income_total: 'إجمالي الوارد',
    income_source_sub: 'مصدر دخل',
    expense_tab_title: 'تفاصيل المصروفات (Expenses)',
    expense_tab_from_budget: 'من الميزانية',
    btn_new_category: '+ فئة جديدة',
    btn_add_expense: 'إضافة مصروف',
    savings_tab_title: 'تفاصيل المدخرات (Savings)',
    savings_tab_target: 'الهدف المخطط:',
    btn_add_savings: 'إضافة مدخرات',
    th_category: 'الفئة',
    th_tracked: 'المسجل',
    th_budget: 'الميزانية',
    th_usage_pct: '% الاستخدام',
    th_visual_bar: 'شريط التقدم',
    th_budget_left: 'المتبقي',
    th_excess: 'الفائض/التجاوز',
    badge_flexible_no_min: 'مرن • بدون حد أدنى',
    label_no_min: 'بدون حد أدنى',
    badge_ready_use: 'جاهز للاستخدام',
    label_emergency_balance: 'رصيد صندوق الطوارئ',
    label_emergency_sub: 'متاح في أي وقت للحالات الطارئة',
    badge_overbudget: 'تجاوز الميزانية (>100%)',
    history_title: 'سجل المعاملات',
    tx_unit: 'معاملات',
    btn_reset_short: 'إعادة ضبط',
    search_placeholder: 'ابحث عن الفئة، المحفظة، الملاحظة...',
    all_types: 'جميع الأنواع',
    th_date: 'التاريخ',
    th_type: 'النوع',
    th_cat_note: 'الفئة والملاحظة',
    th_wallet: 'المحفظة',
    th_amount: 'المبلغ',
    th_action: 'إجراء',
    settings_appearance_title: 'المظهر والعملة واللغة',
    settings_appearance_desc: 'تخصيص الوضع المزدوج (داكن/فاتح)، العملة، ولغة التطبيق',
    settings_theme_label: 'وضع العرض (Dual Mode)',
    theme_dark: 'داكن',
    theme_light: 'فاتح',
    settings_currency_label: 'تنسيق العملة',
    settings_language_label: 'لغة التطبيق',
    settings_security_title: 'كلمة المرور والأمان',
    settings_security_desc: 'قفل التطبيق برمز PIN أو النمط أو بصمة الجهاز',
    sec_status_inactive: 'غير مفعل',
    sec_status_active: 'مفعل',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'النمط',
    sec_method_fingerprint: 'بصمة الإصبع',
    sec_active_method_label: 'الطريقة المفعلة:',
    btn_lock_now: 'قفل الآن',
    btn_change_pass: 'تغيير القفل',
    btn_disable_pass: 'إيقاف القفل',
    fp_not_available_device: 'مستشعر البصمة غير متوفر على هذا الجهاز',
    fp_not_supported_toast: 'هذا الجهاز لا يحتوي على مستشعر بصمة مدعوم، لذا لا يمكن استخدامه.',
    settings_backup_title: 'النسخ الاحتياطي التلقائي في Google Drive',
    settings_backup_desc: 'نسخ المعاملات احتياطياً في الخلفية لحمايتها عند تغيير الجهاز',
    badge_not_logged_in: 'غير مسجل',
    badge_auto_sync: 'مزامنة تلقائية',
    badge_connected: 'متصل',
    backup_device_sync_title: 'مزامنة حساب Google للجهاز',
    backup_device_sync_desc: 'اضغط على "انسخ معاملاتك احتياطياً" بالأسفل لاكتشاف حساب Google في جهازك وتسجيل الدخول أولاً.',
    backup_detected_on: 'تم الاكتشاف على',
    btn_switch_account: 'تبديل الحساب',
    btn_logout: 'خروج',
    backup_auto_bg_label: 'نسخ احتياطي تلقائي في الخلفية (Google Drive)',
    bg_sync_connecting: 'جاري الاتصال بـ Google Drive في الخلفية...',
    bg_sync_uploading: 'جاري نسخ المعاملات والمحافظ إلى Google Drive...',
    bg_sync_done: 'تمت المزامنة تلقائياً مع Google Drive!',
    btn_backup_transactions: 'انسخ معاملاتك احتياطياً',
    btn_restore_transactions: 'استعادة النسخة',
    btn_import_backup: 'استيراد ملف نسخة',
    backup_history_title: 'سجل النسخ الاحتياطي',
    backup_unit: 'نسخ',
    backup_history_empty: 'لا توجد ملفات نسخ احتياطي في Google Drive بعد.',
    settings_report_title: 'تقرير PDF وإدارة البيانات',
    settings_report_desc: 'تنزيل تقرير PDF مباشرة دون تسجيل دخول',
    btn_download_pdf_direct: 'تنزيل التقرير (PDF)',
    btn_full_history: 'سجل المعاملات الكامل',
    btn_export_csv: 'تصدير إلى CSV',
    btn_clear_all: 'تصفير جميع الأرصدة',
    modal_tx_type_label: 'نوع المعاملة',
    modal_tx_cat_label: 'الفئة',
    modal_tx_add_custom_cat: 'إضافة فئة مخصصة',
    modal_tx_amount_label: 'المبلغ',
    modal_tx_date_label: 'التاريخ',
    modal_tx_wallet_label: 'المحفظة',
    modal_tx_no_wallet: 'بدون محفظة',
    modal_tx_note_label: 'ملاحظة',
    modal_tx_optional: '(اختياري)',
    modal_tx_note_placeholder: 'اكتب ملاحظة قصيرة...',
    btn_cancel: 'إلغاء',
    btn_save_tx: 'حفظ المعاملة',
    btn_update_tx: 'تحديث المعاملة',
    modal_cat_title: 'إضافة فئة جديدة',
    modal_cat_group_label: 'المجموعة',
    modal_cat_name_label: 'اسم الفئة الجديدة',
    modal_cat_name_placeholder: 'مثال: ادخار منزل / سفر...',
    btn_add: 'إضافة',
    modal_wallet_bal_title: 'تعديل الرصيد',
    modal_wallet_bal_label: 'الرصيد الحالي',
    btn_save_balance: 'حفظ الرصيد',
    modal_new_wallet_title: 'إضافة محفظة جديدة',
    modal_new_wallet_type: 'نوع المحفظة',
    modal_new_wallet_name: 'اسم المحفظة',
    modal_new_wallet_placeholder: 'اكتب اسم البنك / المحفظة / النقد...',
    modal_new_wallet_initial: 'الرصيد الافتتاحي',
    btn_save_wallet: 'حفظ المحفظة',
    modal_budget_period: 'الفترة:',
    modal_budget_note: 'الدخل وصندوق الطوارئ مرنان ولا يتطلبان ميزانية شهرية مستهدفة.',
    btn_save_budget: 'حفظ الميزانية',
    modal_google_title: 'اكتشاف حساب Google بالجهاز',
    modal_google_sub: 'سجل الدخول لربط النسخ الاحتياطي بـ Google Drive',
    modal_google_scanning_title: 'جاري اكتشاف حسابات Google على هذا الجهاز...',
    modal_google_scanning_sub: 'جاري فحص جلسات حساب Google المحفوظة على جهازك',
    modal_google_detected_label: 'حسابات Google المكتشفة بالجهاز',
    modal_google_pick_btn: 'اختيار وتسجيل دخول',
    modal_google_info: 'يجب تسجيل الدخول أولاً. بعد الدخول والضغط على "انسخ معاملاتك احتياطياً"، سيعمل تلقائياً في الخلفية.',
    modal_google_name_label: 'اسم حساب Google',
    modal_google_email_label: 'البريد الإلكتروني (Gmail)',
    btn_login_connect_device: 'تسجيل الدخول وربط الجهاز',
    modal_sec_title: 'إعداد كلمة المرور',
    modal_sec_sub: 'اختر طريقة قفل التطبيق',
    sec_pin_setup_title: 'إنشاء رمز PIN من 6 أرقام',
    sec_pin_setup_sub: 'اضغط على الأرقام بالأسفل لتعيين رمز PIN',
    btn_save_pin: 'حفظ وتفعيل PIN',
    sec_pattern_setup_title: 'ارسم نمط القفل (4 نقاط على الأقل)',
    sec_pattern_setup_sub: 'صل النقاط في الشبكة 3x3 بالأسفل',
    btn_reset_pattern: 'إعادة الرسم',
    btn_save_pattern: 'حفظ النمط',
    sec_fp_setup_title: 'بصمة إصبع الجهاز',
    sec_fp_setup_sub: 'استخدم مستشعر البصمة الفعلي في جهازك لقفل التطبيق.',
    sec_fp_click_scan: 'اضغط على المستشعر لفحص بصمة الجهاز',
    lock_screen_title: 'التطبيق مقفل',
    lock_screen_pin_prompt: 'أدخل رمز PIN المكون من 6 أرقام',
    lock_screen_pattern_prompt: 'ارسم نمط القفل على الشبكة 3x3',
    lock_screen_fp_prompt: 'تحقق من بصمة جهازك لفتح القفل',
    lock_screen_forgot: 'نسيت كلمة المرور؟ إعادة ضبط'
  },
  es: {
    nav_dashboard: 'Panel',
    nav_wallets: 'Billeteras',
    nav_income: 'Ingresos',
    nav_expense: 'Gastos',
    nav_savings: 'Ahorros',
    nav_history: 'Historial',
    nav_settings: 'Ajustes',
    nav_home_mobile: 'Inicio',
    btn_budget_short: 'Presup.',
    btn_add_tx: 'Añadir Transacción',
    btn_edit_tx: 'Editar Transacción',
    btn_monthly_budget: 'Presupuesto Mensual',
    open_month_period: 'Meses Disponibles',
    all_months_1_year: 'Todos los Meses (1 Año)',
    card_total_income: 'Ingresos Totales',
    card_total_expense: 'Gastos Totales',
    card_total_savings: 'Ahorros Totales',
    card_total_balance: 'Saldo Total',
    btn_open_wallet: 'Abrir Billeteras',
    sec_analytics: 'Analítica Visual',
    chart_top_spending: 'Mayores Gastos',
    chart_top_spending_sub: 'Categorías de gasto',
    chart_savings_dist: 'Dist. de Ahorros',
    chart_savings_dist_sub: 'Asignación de ahorros',
    chart_actual_vs_budget: 'Real vs Presupuesto',
    chart_actual_vs_budget_sub: 'Gasto mensual vs presupuesto',
    chart_actual_label: 'Real',
    chart_budget_label: 'Presupuesto',
    chart_empty: 'Vacío',
    sec_recent_tx: 'Transacciones Recientes',
    btn_view_all: 'Ver Todo',
    empty_tx_period: 'No hay transacciones registradas en este período',
    dashboard_total_all_balance: 'TOTAL DE TODOS LOS SALDOS',
    dashboard_all_balance_desc: 'Saldo total acumulado de todas las fuentes activas (Cuentas bancarias, Billeteras digitales y Efectivo).',
    btn_manage_wallets: 'Gestionar Billeteras',
    wallet_total_title: 'Saldo Total en Billeteras',
    wallet_hero_desc: 'Supervise y gestione sus cuentas bancarias, billeteras digitales y efectivo en un solo lugar.',
    btn_add_wallet: 'Añadir Billetera',
    wallet_cat_bank: 'Banco',
    wallet_cat_cash: 'Efectivo',
    wallet_cat_ewallet: 'E-Wallet',
    wallet_account_unit: 'Cuentas',
    wallet_list_title: 'Lista de Fondos',
    wallet_list_desc: 'Seleccione una categoría para ver el saldo detallado de cada billetera.',
    filter_all: 'Todos',
    wallet_empty_all_title: 'Aún No Hay Billeteras Guardadas',
    wallet_empty_all_desc: 'Añada sus cuentas bancarias, billeteras digitales o efectivo para registrar sus saldos automáticamente.',
    wallet_empty_bank_title: 'Sin Cuentas Bancarias',
    wallet_empty_bank_desc: 'Añada su cuenta bancaria para supervisar su saldo.',
    wallet_empty_cash_title: 'Sin Billetera de Efectivo',
    wallet_empty_cash_desc: 'Añada una billetera de efectivo para gastos diarios.',
    wallet_empty_ewallet_title: 'Sin Billetera Digital',
    wallet_empty_ewallet_desc: 'Añada su billetera digital para supervisar pagos.',
    wallet_btn_set_balance: 'Ajustar Saldo',
    wallet_stored_balance: 'Saldo Guardado',
    wallet_in: 'Entrada',
    wallet_out: 'Salida',
    wallet_share: 'Proporción',
    income_tab_title: 'Desglose de Ingresos',
    income_tab_sub: 'Total fondos recibidos',
    btn_new_source: '+ Nueva Fuente',
    btn_add_income: 'Añadir Ingreso',
    th_income_source: 'Fuente de Ingreso',
    th_income_share: 'Aporte (%)',
    th_income_bar: 'Proporción de Ingreso',
    th_income_total: 'Total Recibido',
    income_source_sub: 'Fuente de ingresos',
    expense_tab_title: 'Desglose de Gastos',
    expense_tab_from_budget: 'del presupuesto',
    btn_new_category: '+ Nueva Categoría',
    btn_add_expense: 'Añadir Gasto',
    savings_tab_title: 'Desglose de Ahorros',
    savings_tab_target: 'Meta planificada:',
    btn_add_savings: 'Añadir Ahorro',
    th_category: 'Categoría',
    th_tracked: 'Registrado',
    th_budget: 'Presupuesto',
    th_usage_pct: '% Uso',
    th_visual_bar: 'Barra de Progreso',
    th_budget_left: 'Restante',
    th_excess: 'Exceso',
    badge_flexible_no_min: 'Flexible • Sin Mínimo',
    label_no_min: 'Sin Mínimo',
    badge_ready_use: 'Listo para Usar',
    label_emergency_balance: 'Saldo Fondo de Emergencia',
    label_emergency_sub: 'Disponible en cualquier momento de emergencia',
    badge_overbudget: 'Sobre Presupuesto (>100%)',
    history_title: 'Historial de Transacciones',
    tx_unit: 'Transacciones',
    btn_reset_short: 'Reiniciar',
    search_placeholder: 'Buscar categoría, billetera, nota...',
    all_types: 'Todos los Tipos',
    th_date: 'Fecha',
    th_type: 'Tipo',
    th_cat_note: 'Categoría y Nota',
    th_wallet: 'Billetera',
    th_amount: 'Monto',
    th_action: 'Acción',
    settings_appearance_title: 'Apariencia, Moneda e Idioma',
    settings_appearance_desc: 'Configure Modo Dual (Oscuro/Claro), formato de moneda e idioma',
    settings_theme_label: 'Modo de Pantalla (Dual Mode)',
    theme_dark: 'Oscuro',
    theme_light: 'Claro',
    settings_currency_label: 'Formato de Moneda',
    settings_language_label: 'Idioma de la App',
    settings_security_title: 'Contraseña y Seguridad',
    settings_security_desc: 'Bloquee la app con PIN, Patrón o Huella del dispositivo',
    sec_status_inactive: 'Inactivo',
    sec_status_active: 'Activo',
    sec_method_pin: 'PIN',
    sec_method_pattern: 'Patrón',
    sec_method_fingerprint: 'Huella Digital',
    sec_active_method_label: 'Método Activo:',
    btn_lock_now: 'Bloquear Ahora',
    btn_change_pass: 'Cambiar Clave',
    btn_disable_pass: 'Desactivar',
    fp_not_available_device: 'El sensor de huella no está disponible en este dispositivo',
    fp_not_supported_toast: 'Este dispositivo no tiene un sensor de Huella Digital compatible, por lo que no se puede usar.',
    settings_backup_title: 'Copia Automática en Google Drive',
    settings_backup_desc: 'Respalde sus transacciones en segundo plano para no empezar de 0 al cambiar de dispositivo',
    badge_not_logged_in: 'Sin Sesión',
    badge_auto_sync: 'Auto-Sync Activo',
    badge_connected: 'Conectado',
    backup_device_sync_title: 'Sincronización con Cuenta Google del Dispositivo',
    backup_device_sync_desc: 'Haga clic en "Respaldar sus Transacciones" abajo para detectar la cuenta Google en este dispositivo e iniciar sesión primero.',
    backup_detected_on: 'Detectado en',
    btn_switch_account: 'Cambiar Cuenta',
    btn_logout: 'Salir',
    backup_auto_bg_label: 'Copia Automática en Segundo Plano (Google Drive)',
    bg_sync_connecting: 'Conectando con Google Drive en segundo plano...',
    bg_sync_uploading: 'Respaldando transacciones y billeteras en Google Drive...',
    bg_sync_done: '¡Sincronizado automáticamente con Google Drive!',
    btn_backup_transactions: 'Respaldar sus Transacciones',
    btn_restore_transactions: 'Restaurar Copia',
    btn_import_backup: 'Importar Archivo',
    backup_history_title: 'Historial de Copias de Seguridad',
    backup_unit: 'Copias',
    backup_history_empty: 'Aún no hay archivos de respaldo en Google Drive.',
    settings_report_title: 'Informe PDF y Gestión de Datos',
    settings_report_desc: 'Descargue el informe PDF directamente sin iniciar sesión',
    btn_download_pdf_direct: 'Descargar Informe (PDF)',
    btn_full_history: 'Historial Completo',
    btn_export_csv: 'Exportar a CSV',
    btn_clear_all: 'Restablecer Saldos a 0',
    modal_tx_type_label: 'Tipo de Transacción',
    modal_tx_cat_label: 'Categoría',
    modal_tx_add_custom_cat: 'Añadir Categoría Propia',
    modal_tx_amount_label: 'Monto',
    modal_tx_date_label: 'Fecha',
    modal_tx_wallet_label: 'Billetera',
    modal_tx_no_wallet: 'Sin Billetera',
    modal_tx_note_label: 'Nota',
    modal_tx_optional: '(Opcional)',
    modal_tx_note_placeholder: 'Escriba una nota breve...',
    btn_cancel: 'Cancelar',
    btn_save_tx: 'Guardar Transacción',
    btn_update_tx: 'Actualizar Transacción',
    modal_cat_title: 'Añadir Nueva Categoría',
    modal_cat_group_label: 'Grupo',
    modal_cat_name_label: 'Nombre de la Categoría',
    modal_cat_name_placeholder: 'Ej: Ahorro Casa / Vacaciones...',
    btn_add: 'Añadir',
    modal_wallet_bal_title: 'Ajustar Saldo',
    modal_wallet_bal_label: 'Saldo Actual',
    btn_save_balance: 'Guardar Saldo',
    modal_new_wallet_title: 'Añadir Nueva Billetera',
    modal_new_wallet_type: 'Tipo de Billetera',
    modal_new_wallet_name: 'Nombre de Billetera',
    modal_new_wallet_placeholder: 'Escriba nombre de Banco / E-Wallet / Efectivo...',
    modal_new_wallet_initial: 'Saldo Inicial',
    btn_save_wallet: 'Guardar Billetera',
    modal_budget_period: 'Período:',
    modal_budget_note: 'Los Ingresos y el Fondo de Emergencia son flexibles y no requieren un presupuesto mensual mínimo.',
    btn_save_budget: 'Guardar Presupuesto',
    modal_google_title: 'Detectar Cuenta Google del Dispositivo',
    modal_google_sub: 'Inicie sesión para vincular el respaldo con Google Drive',
    modal_google_scanning_title: 'Detectando Cuentas Google en Este Dispositivo...',
    modal_google_scanning_sub: 'Verificando sesiones de Google guardadas en su dispositivo',
    modal_google_detected_label: 'Cuentas Google Detectadas',
    modal_google_pick_btn: 'Elegir e Iniciar Sesión',
    modal_google_info: 'Primero debe iniciar sesión. Luego de iniciar sesión y pulsar "Respaldar sus Transacciones", se sincronizará en segundo plano con Google Drive.',
    modal_google_name_label: 'Nombre de Cuenta Google',
    modal_google_email_label: 'Correo Google (Gmail)',
    btn_login_connect_device: 'Iniciar Sesión y Conectar',
    modal_sec_title: 'Configurar Contraseña',
    modal_sec_sub: 'Elija un método de bloqueo',
    sec_pin_setup_title: 'Crear PIN de 6 Dígitos',
    sec_pin_setup_sub: 'Pulse los números abajo para definir su PIN',
    btn_save_pin: 'Guardar y Activar PIN',
    sec_pattern_setup_title: 'Dibujar Patrón (Mín. 4 Puntos)',
    sec_pattern_setup_sub: 'Conecte los puntos en la cuadrícula 3x3',
    btn_reset_pattern: 'Repetir Patrón',
    btn_save_pattern: 'Guardar Patrón',
    sec_fp_setup_title: 'Huella Digital del Dispositivo',
    sec_fp_setup_sub: 'Use el sensor biométrico integrado en su dispositivo para bloquear la app.',
    sec_fp_click_scan: 'Toque el sensor para verificar su huella',
    lock_screen_title: 'FinanceTracker Bloqueado',
    lock_screen_pin_prompt: 'Ingrese su PIN de seguridad de 6 dígitos',
    lock_screen_pattern_prompt: 'Dibuje su patrón de desbloqueo en la cuadrícula 3x3',
    lock_screen_fp_prompt: 'Verifique el sensor de huella de su dispositivo para desbloquear',
    lock_screen_forgot: '¿Olvidó su clave? Reiniciar'
  }
};

// Sinkronisasi seluruh alias kunci translasi (i18n) untuk semua 8 bahasa agar tidak ada kode/key mentah yang tampil di UI
const I18N_KEY_ALIASES = {
  wallet_accounts_suffix: 'wallet_account_unit',
  btn_reset: 'btn_reset_short',
  wallet_bank_label: 'wallet_cat_bank',
  wallet_ewallet_label: 'wallet_cat_ewallet',
  wallet_cash_label: 'wallet_cat_cash',
  wallet_saved_balance: 'wallet_stored_balance',
  th_total_in: 'th_income_total',
  footer_total_income: 'card_total_income',
  footer_total_expense: 'card_total_expense',
  footer_total_savings: 'card_total_savings',
  no_min_budget_badge: 'badge_flexible_no_min',
  no_min_label: 'label_no_min',
  ready_to_use_badge: 'badge_ready_use',
  over_budget_badge: 'badge_overbudget',
  btn_set_budget: 'btn_monthly_budget',
  emergency_fund_balance: 'label_emergency_balance',
  emergency_fund_sub: 'label_emergency_sub',
  th_monthly_budget: 'th_budget',
  th_left: 'th_budget_left',
  chart_empty_label: 'chart_empty',
  chart_actual_legend: 'chart_actual_label',
  chart_budget_legend: 'chart_budget_label',
  modal_tx_edit_title: 'btn_edit_tx',
  tx_count_suffix: 'tx_unit',
  tx_empty_period: 'empty_tx_period',
  drive_status_autosync: 'badge_auto_sync',
  drive_status_connected: 'badge_connected',
  drive_status_unconnected: 'badge_not_logged_in',
  drive_backups_count_suffix: 'backup_unit',
  drive_device_sync_title: 'backup_device_sync_title',
  drive_device_sync_desc: 'backup_device_sync_desc',
  drive_detected_on: 'backup_detected_on',
  drive_btn_switch_acc: 'btn_switch_account',
  drive_btn_logout: 'btn_logout',
  drive_bg_auto_label: 'backup_auto_bg_label',
  drive_empty_backups: 'backup_history_empty',
  modal_gauth_scanning: 'modal_google_scanning_title',
  modal_gauth_first_time: 'modal_google_info',
  modal_gauth_pick_btn: 'modal_google_pick_btn',
  sec_pin_title: 'sec_method_pin',
  sec_pattern_title: 'sec_method_pattern',
  sec_fp_title: 'sec_method_fingerprint',
  fp_not_supported_desc: 'fp_not_available_device',
  fp_not_supported_title: 'fp_not_available_device',
  sec_active_method: 'sec_active_method_label',
  sec_btn_lock_now: 'btn_lock_now',
  sec_btn_change: 'btn_change_pass',
  sec_btn_disable: 'btn_disable_pass',
  modal_sec_pin_heading: 'sec_pin_setup_title',
  modal_sec_pin_sub: 'sec_pin_setup_sub',
  modal_sec_pin_save: 'btn_save_pin',
  modal_sec_pattern_heading: 'sec_pattern_setup_title',
  modal_sec_pattern_sub: 'sec_pattern_setup_sub',
  modal_sec_pattern_reset: 'btn_reset_pattern',
  modal_sec_pattern_save: 'btn_save_pattern',
  modal_sec_fp_heading: 'sec_fp_setup_title',
  modal_sec_fp_sub: 'sec_fp_setup_sub',
  modal_sec_fp_status: 'sec_fp_click_scan',
  lock_prompt_pin: 'lock_screen_pin_prompt',
  lock_prompt_pattern: 'lock_screen_pattern_prompt',
  lock_prompt_fp: 'lock_screen_fp_prompt',
  lock_fp_tap: 'sec_fp_click_scan',
  month_picker_title: 'open_month_period',
  month_picker_all_year: 'all_months_1_year',
  tx_without_wallet: 'modal_tx_no_wallet',
  modal_tx_submit: 'btn_save_tx',
  modal_tx_update: 'btn_update_tx',
  modal_addwal_name_label: 'modal_new_wallet_name',
  modal_budget_period_prefix: 'modal_budget_period',
  modal_budget_title: 'btn_monthly_budget',
  th_tx_date: 'th_date',
  th_tx_type: 'th_type',
  th_tx_category: 'th_category',
  th_tx_amount: 'th_amount',
  th_tx_wallet: 'th_wallet'
};

const EXTRA_GOOGLE_I18N = {
  id: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Registrasi & sinkronisasi mudah menggunakan Google',
    google_header_login: 'Login dengan Google',
    google_step1_title: 'Pilih akun',
    google_step1_sub: 'Lanjutkan ke FinanceTracker',
    google_use_another_acc: 'Gunakan akun lain',
    google_other_email_placeholder: 'Masukkan alamat email Google Anda...',
    google_step1_policy: 'Sebelum menggunakan aplikasi ini, Anda dapat meninjau Kebijakan Privasi dan Persyaratan Layanan FinanceTracker.',
    google_footer_help: 'Bantuan',
    google_footer_privacy: 'Privasi',
    google_footer_terms: 'Persyaratan',
    google_step2_title: 'Login ke FinanceTracker',
    google_step2_allow_title: 'Google akan mengizinkan FinanceTracker mengakses info tentang Anda ini',
    google_step2_email_label: 'Alamat email',
    google_step2_policy_1: 'Tinjau Kebijakan Privasi dan Persyaratan Layanan FinanceTracker untuk memahami cara FinanceTracker memproses dan melindungi data Anda.',
    google_step2_policy_2: 'Untuk melakukan perubahan kapan saja, buka Akun Google Anda.',
    google_step2_policy_3: 'Pelajari lebih lanjut Login dengan Google.',
    google_btn_continue: 'Lanjutkan',
    google_step3_banner_sub: 'Silakan isi nama Anda di bawah ini',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'Nama Anda',
    google_step3_name_placeholder: 'Ketik nama panggilan / lengkap Anda',
    google_step3_terms: 'Saya menyetujui Ketentuan Layanan (Terms of Use)',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Akun Google Anda kini telah terhubung dengan FinanceTracker dan siap mencadangkan transaksi secara otomatis.',
    google_btn_done: 'Mulai Gunakan',
    google_connecting_label: 'Menghubungkan akun Google...',
    modal_google_info: 'Klik akun Google yang terhubung di perangkat Anda di atas untuk langsung terhubung ke aplikasi.'
  },
  en: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Seamless registration & backup using Google',
    google_header_login: 'Sign in with Google',
    google_step1_title: 'Choose an account',
    google_step1_sub: 'to continue to FinanceTracker',
    google_use_another_acc: 'Use another account',
    google_other_email_placeholder: 'Enter your Google email address...',
    google_step1_policy: 'Before using this app, you can review FinanceTracker’s Privacy Policy and Terms of Service.',
    google_footer_help: 'Help',
    google_footer_privacy: 'Privacy',
    google_footer_terms: 'Terms',
    google_step2_title: 'Sign in to FinanceTracker',
    google_step2_allow_title: 'Google will allow FinanceTracker to access this info about you',
    google_step2_email_label: 'Email address',
    google_step2_policy_1: 'Review FinanceTracker’s Privacy Policy and Terms of Service to understand how FinanceTracker processes and protects your data.',
    google_step2_policy_2: 'To make changes at any time, go to your Google Account.',
    google_step2_policy_3: 'Learn more about Sign in with Google.',
    google_btn_continue: 'Continue',
    google_step3_banner_sub: 'Please fill in your name below',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'Your Name',
    google_step3_name_placeholder: 'Enter your display name',
    google_step3_terms: 'I agree to the Terms of Use',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Your Google account is now connected to FinanceTracker and ready for automatic cloud backups.',
    google_btn_done: 'Get Started',
    google_connecting_label: 'Connecting Google account...',
    modal_google_info: 'Click your device-linked Google account above to connect directly to the app.'
  },
  ms: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Pendaftaran & sandaran mudah menggunakan Google',
    google_header_login: 'Log masuk dengan Google',
    google_step1_title: 'Pilih akaun',
    google_step1_sub: 'Teruskan ke FinanceTracker',
    google_use_another_acc: 'Gunakan akaun lain',
    google_other_email_placeholder: 'Masukkan alamat e-mel Google anda...',
    google_step1_policy: 'Sebelum menggunakan aplikasi ini, anda boleh menyemak Dasar Privasi dan Syarat Perkhidmatan FinanceTracker.',
    google_footer_help: 'Bantuan',
    google_footer_privacy: 'Privasi',
    google_footer_terms: 'Syarat',
    google_step2_title: 'Log masuk ke FinanceTracker',
    google_step2_allow_title: 'Google akan membenarkan FinanceTracker mengakses maklumat tentang anda ini',
    google_step2_email_label: 'Alamat e-mel',
    google_step2_policy_1: 'Semak Dasar Privasi dan Syarat Perkhidmatan FinanceTracker untuk memahami cara data anda dilindungi.',
    google_step2_policy_2: 'Untuk membuat perubahan pada bila-bila masa, buka Akaun Google anda.',
    google_step2_policy_3: 'Ketahui lebih lanjut tentang Log masuk dengan Google.',
    google_btn_continue: 'Teruskan',
    google_step3_banner_sub: 'Sila isi nama anda di bawah',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'Nama Anda',
    google_step3_name_placeholder: 'Masukkan nama anda',
    google_step3_terms: 'Saya bersetuju dengan Terma Penggunaan (Terms of Use)',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Akaun Google anda kini disambungkan dengan FinanceTracker.',
    google_btn_done: 'Mula Gunakan',
    google_connecting_label: 'Menyambungkan akaun Google...',
    modal_google_info: 'Klik akaun Google pada peranti anda di atas untuk terus bersambung ke aplikasi.'
  },
  ja: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Google を使用したシームレスな連携とバックアップ',
    google_header_login: 'Google でログイン',
    google_step1_title: 'アカウントの選択',
    google_step1_sub: 'FinanceTracker に移動',
    google_use_another_acc: '別のアカウントを使用',
    google_other_email_placeholder: 'Google メールアドレスを入力...',
    google_step1_policy: 'このアプリを使用する前に、FinanceTracker のプライバシーポリシーと利用規約をご確認ください。',
    google_footer_help: 'ヘルプ',
    google_footer_privacy: 'プライバシー',
    google_footer_terms: '規約',
    google_step2_title: 'FinanceTracker にログイン',
    google_step2_allow_title: 'Google は FinanceTracker に次の情報へのアクセスを許可します',
    google_step2_email_label: 'メールアドレス',
    google_step2_policy_1: 'FinanceTracker のプライバシーポリシーと利用規約をご確認ください。',
    google_step2_policy_2: 'いつでも Google アカウントから設定を変更できます。',
    google_step2_policy_3: 'Google でログインの詳細。',
    google_btn_continue: '次へ',
    google_step3_banner_sub: '以下にあなたの名前を入力してください',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'お名前',
    google_step3_name_placeholder: 'お名前を入力',
    google_step3_terms: '利用規約 (Terms of Use) に同意します',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Google アカウントが FinanceTracker に正常にリンクされました。',
    google_btn_done: 'はじめる',
    google_connecting_label: 'Google アカウントに接続中...',
    modal_google_info: '上のデバイスの Google アカウントをクリックすると、すぐにアプリと連携されます。'
  },
  ko: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Google을 사용한 간편 등록 및 자동 백업',
    google_header_login: 'Google 계정으로 로그인',
    google_step1_title: '계정 선택',
    google_step1_sub: 'FinanceTracker(으)로 이동',
    google_use_another_acc: '다른 계정 사용',
    google_other_email_placeholder: 'Google 이메일 주소 입력...',
    google_step1_policy: '이 앱을 사용하기 전에 FinanceTracker의 개인정보처리방침 및 서비스 약관을 검토할 수 있습니다.',
    google_footer_help: '도움말',
    google_footer_privacy: '개인정보처리방침',
    google_footer_terms: '약관',
    google_step2_title: 'FinanceTracker에 로그인',
    google_step2_allow_title: 'Google에서 FinanceTracker이(가) 다음 정보에 액세스하도록 허용합니다',
    google_step2_email_label: '이메일 주소',
    google_step2_policy_1: 'FinanceTracker의 개인정보처리방침 및 서비스 약관을 확인하세요.',
    google_step2_policy_2: '언제든지 Google 계정에서 변경할 수 있습니다.',
    google_step2_policy_3: 'Google 계정으로 로그인 자세히 알아보기.',
    google_btn_continue: '계속',
    google_step3_banner_sub: '아래에 이름을 입력해 주세요',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: '이름',
    google_step3_name_placeholder: '이름 입력',
    google_step3_terms: '이용약관 (Terms of Use)에 동의합니다',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Google 계정이 FinanceTracker에 연결되었습니다.',
    google_btn_done: '시작하기',
    google_connecting_label: 'Google 계정 연결 중...',
    modal_google_info: '위의 기기에 연결된 Google 계정을 클릭하면 즉시 앱에 연결됩니다.'
  },
  zh: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: '使用 Google 轻松关联与自动备份',
    google_header_login: '使用 Google 账号登录',
    google_step1_title: '选择账号',
    google_step1_sub: '继续前往 FinanceTracker',
    google_use_another_acc: '使用其他账号',
    google_other_email_placeholder: '输入您的 Google 邮箱地址...',
    google_step1_policy: '在使用此应用之前，您可以先查看 FinanceTracker 的隐私权政策和服务条款。',
    google_footer_help: '帮助',
    google_footer_privacy: '隐私权',
    google_footer_terms: '条款',
    google_step2_title: '登录 FinanceTracker',
    google_step2_allow_title: 'Google 将允许 FinanceTracker 访问您的以下信息',
    google_step2_email_label: '电子邮件地址',
    google_step2_policy_1: '请查看 FinanceTracker 的隐私权政策和服务条款。',
    google_step2_policy_2: '您可以随时前往 Google 账号进行更改。',
    google_step2_policy_3: '详细了解“使用 Google 账号登录”。',
    google_btn_continue: '继续',
    google_step3_banner_sub: '请在下方填写您的姓名',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: '您的姓名',
    google_step3_name_placeholder: '请输入您的姓名',
    google_step3_terms: '我同意服务条款 (Terms of Use)',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: '您的 Google 账号已成功连接至 FinanceTracker。',
    google_btn_done: '开始使用',
    google_connecting_label: '正在连接 Google 账号...',
    modal_google_info: '点击上方设备关联的 Google 账号即可直接连接至应用。'
  },
  ar: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'التسجيل والنسخ الاحتياطي السلس باستخدام Google',
    google_header_login: 'تسجيل الدخول باستخدام Google',
    google_step1_title: 'اختيار حساب',
    google_step1_sub: 'للمتابعة إلى FinanceTracker',
    google_use_another_acc: 'استخدام حساب آخر',
    google_other_email_placeholder: 'أدخل بريد Google الإلكتروني...',
    google_step1_policy: 'قبل استخدام هذا التطبيق، يمكنك مراجعة سياسة الخصوصية وبنود الخدمة في FinanceTracker.',
    google_footer_help: 'مساعدة',
    google_footer_privacy: 'الخصوصية',
    google_footer_terms: 'البنود',
    google_step2_title: 'تسجيل الدخول إلى FinanceTracker',
    google_step2_allow_title: 'ستسمح Google لتطبيق FinanceTracker بالوصول إلى هذه المعلومات عنك',
    google_step2_email_label: 'عنوان البريد الإلكتروني',
    google_step2_policy_1: 'راجع سياسة الخصوصية وبنود الخدمة الخاصة بـ FinanceTracker.',
    google_step2_policy_2: 'لإجراء تغييرات في أي وقت، انتقل إلى حساب Google الخاص بك.',
    google_step2_policy_3: 'مزيد من المعلومات حول تسجيل الدخول باستخدام Google.',
    google_btn_continue: 'متابعة',
    google_step3_banner_sub: 'يرجى إدخال اسمك أدناه',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'الاسم',
    google_step3_name_placeholder: 'أدخل اسمك',
    google_step3_terms: 'أوافق على شروط الاستخدام (Terms of Use)',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'تم ربط حساب Google الخاص بك بنجاح مع FinanceTracker.',
    google_btn_done: 'ابدأ الآن',
    google_connecting_label: 'جارٍ ربط حساب Google...',
    modal_google_info: 'انقر فوق حساب Google المرتبط بجهازك أعلاه للاتصال بالتطبيق مباشرةً.'
  },
  es: {
    btn_login_with_google: 'Continue with Google',
    google_seamless_sub: 'Registro y respaldo sin complicaciones con Google',
    google_header_login: 'Iniciar sesión con Google',
    google_step1_title: 'Elige una cuenta',
    google_step1_sub: 'para ir a FinanceTracker',
    google_use_another_acc: 'Usar otra cuenta',
    google_other_email_placeholder: 'Ingresa tu correo de Google...',
    google_step1_policy: 'Antes de usar esta aplicación, puedes revisar la Política de Privacidad y las Condiciones del Servicio de FinanceTracker.',
    google_footer_help: 'Ayuda',
    google_footer_privacy: 'Privacidad',
    google_footer_terms: 'Condiciones',
    google_step2_title: 'Inicia sesión en FinanceTracker',
    google_step2_allow_title: 'Google permitirá que FinanceTracker acceda a esta información sobre ti',
    google_step2_email_label: 'Dirección de correo electrónico',
    google_step2_policy_1: 'Revisa la Política de Privacidad y las Condiciones del Servicio de FinanceTracker.',
    google_step2_policy_2: 'Para realizar cambios en cualquier momento, ve a tu Cuenta de Google.',
    google_step2_policy_3: 'Más información sobre cómo Iniciar sesión con Google.',
    google_btn_continue: 'Continuar',
    google_step3_banner_sub: 'Por favor ingresa tu nombre abajo',
    google_step3_email_label: 'E-mail',
    google_step3_name_label: 'Tu Nombre',
    google_step3_name_placeholder: 'Escribe tu nombre',
    google_step3_terms: 'Acepto los Términos de Uso (Terms of Use)',
    google_btn_confirm: 'Confirm',
    google_welcome_prefix: 'Selamat Datang,',
    google_welcome_sub: 'Tu cuenta de Google ahora está conectada a FinanceTracker.',
    google_btn_done: 'Comenzar',
    google_connecting_label: 'Conectando cuenta de Google...',
    modal_google_info: 'Haga clic en su cuenta de Google vinculada al dispositivo arriba para conectarse directamente.'
  }
};

Object.keys(I18N_TRANSLATIONS).forEach((langCode) => {
  const dict = I18N_TRANSLATIONS[langCode];
  if (EXTRA_GOOGLE_I18N[langCode]) {
    Object.assign(dict, EXTRA_GOOGLE_I18N[langCode]);
  }
  Object.entries(I18N_KEY_ALIASES).forEach(([aliasKey, sourceKey]) => {
    if (!(aliasKey in dict) && sourceKey in dict) {
      dict[aliasKey] = dict[sourceKey];
    }
  });
  dict.modal_gauth_first_time = dict.modal_google_info;
});

const MONTHS_ID = MONTHS_BY_LANG.id;
const MONTHS_SHORT_ID = MONTHS_SHORT_BY_LANG.id;

function getTodayLocalISO() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function getCurrentDateInfo(langCode = 'id') {
  const now = new Date();
  const langObj = SUPPORTED_LANGUAGES.find((l) => l.code === langCode) || SUPPORTED_LANGUAGES[0];
  const formattedToday = now.toLocaleDateString(langObj.locale, {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  return {
    day: now.getDate(),
    month: now.getMonth(),
    year: now.getFullYear(),
    isoDate: getTodayLocalISO(),
    formattedToday
  };
}

function getInitialTransactions() {
  return [];
}

function getInitialBudgets() {
  return {};
}
